event_inherited();
up_sprite = spr_martlet_up;
right_sprite = spr_martlet_right;
down_sprite = spr_martlet_down;
left_sprite = spr_martlet_left;
up_sprite_idle = spr_martlet_up_talk;
right_sprite_idle = spr_martlet_right_talk;
down_sprite_idle = spr_martlet_down_talk;
left_sprite_idle = spr_martlet_left_talk;
action_sprite = false;
scene = 0;
can_walk = true;
x_dest[0] = 360;
y_dest[0] = y;
actor_speed = 3;
axis_override = "x";
end_direction = "left";
walk_collider = -4;
