image_speed = 0.35;
gateid = 0;
depthplus = 1;
durationspeed = 2;
durationspeedy = 5;
x_move = 0;
y_move = 0;
eggsprite = spr_gateegg_opened;
randomize();
paletteselect = floor(irandom(sprite_get_width(spr_eggpalette) - 1));
