event_inherited();
state = 0;
destX = [200, acv_blaster_approach];
destY = [200, acv_blaster_approach];
destAngle = [90, acv_blaster_approach];
approachTimer = 0;
image_xscale = 1;
image_yscale = 1;
image_speed = 0;
rotateAfter = false;
delay = 8;
collisionsOn = false;
blastThicc = 0;
bulletTimer = 0;
fade = 1;
terminal = 10;
bb = 0;
bbsiner = 0;
karma = 10;
bodyCollisions = true;
fakeFireVisuals = false;
drawPost = false;
xBlastSpeed = 0;
handledDamageThisFrame = false;
hover = false;
hoverSiner = 0;
sfx_play_ext(snd_segapower, 0.8, 1.2, 80, false);
