starting_point_x = x;
starting_point_y = y;
draw_position_x = starting_point_x;
draw_position_y = starting_point_y;
damage_disjoint_x = 0;
damage_disjoint_y = 0;
damage_disjoint_count = 0;
no_loop_damage_disjoint_count = false;
no_loop_create_clouds = false;
image_speed = 0;
image_index = 0;
instance_create(x - 4, y - 102, obj_dummy_training_hat);
