scr_initinput();
hsp = 0;
vsp = 0;
grav = 0.4;
xscale = 1;
movespeed = 0;
grounded = false;
grinding = false;
state = ballstates.air;
hspinvert = 0;
vspinvert = 0;
anglevertx = 0;
changeangle = 0;
angledirect = 0;
inprogrsangle = 0;
