function __scribble_effects_maps_initialize()
{
    var _map = __scribble_get_effects_map();
    var _slash_map = __scribble_get_effects_slash_map();
    ds_map_set(_map, "wave", 1);
    ds_map_set(_map, "shake", 2);
    ds_map_set(_map, "rainbow", 3);
    ds_map_set(_map, "wobble", 4);
    ds_map_set(_map, "pulse", 5);
    ds_map_set(_map, "wheel", 6);
    ds_map_set(_map, "cycle", 7);
    ds_map_set(_map, "jitter", 8);
    ds_map_set(_map, "blink", 9);
    ds_map_set(_map, "slant", 10);
    ds_map_set(_slash_map, "/wave", 1);
    ds_map_set(_slash_map, "/shake", 2);
    ds_map_set(_slash_map, "/rainbow", 3);
    ds_map_set(_slash_map, "/wobble", 4);
    ds_map_set(_slash_map, "/pulse", 5);
    ds_map_set(_slash_map, "/wheel", 6);
    ds_map_set(_slash_map, "/cycle", 7);
    ds_map_set(_slash_map, "/jitter", 8);
    ds_map_set(_slash_map, "/blink", 9);
    ds_map_set(_slash_map, "/slant", 10);
    ds_map_set(_map, "WAVE", 1);
    ds_map_set(_map, "SHAKE", 2);
    ds_map_set(_map, "RAINBOW", 3);
    ds_map_set(_map, "WOBBLE", 4);
    ds_map_set(_map, "PULSE", 5);
    ds_map_set(_map, "WHEEL", 6);
    ds_map_set(_map, "CYCLE", 7);
    ds_map_set(_map, "JITTER", 8);
    ds_map_set(_map, "BLINK", 9);
    ds_map_set(_map, "SLANT", 10);
    ds_map_set(_slash_map, "/WAVE", 1);
    ds_map_set(_slash_map, "/SHAKE", 2);
    ds_map_set(_slash_map, "/RAINBOW", 3);
    ds_map_set(_slash_map, "/WOBBLE", 4);
    ds_map_set(_slash_map, "/PULSE", 5);
    ds_map_set(_slash_map, "/WHEEL", 6);
    ds_map_set(_slash_map, "/CYCLE", 7);
    ds_map_set(_slash_map, "/JITTER", 8);
    ds_map_set(_slash_map, "/BLINK", 9);
    ds_map_set(_slash_map, "/SLANT", 10);
}
