active = 0;
image_speed = 1;
spr_idle = spr_butterbuddy_idle;
spr_talk = spr_butterbuddy_talk;
borderTargetpos = -160;
borderX = 32 + wave(-2, 2, 4, 0);
borderY = borderTargetpos;
borderscaleYmult = 1;
borderVsp = 0;
borderpart = 0;
text = "Get it Get it Done Get it Get it done Do your dance Get it Get it Done Get it Get it done Let me hear you say!";
depth = 10;
scribble_anim_wave(1, 3, 1);
