event_inherited();
collectvanish = false;
collectboxid = -4;
use_palette = true;
in_the_void = false;
sprite_index = choose(obj_player.spr_smallcollect1, obj_player.spr_smallcollect2, obj_player.spr_smallcollect3, obj_player.spr_smallcollect4, obj_player.spr_smallcollect5);
image_index = irandom(image_number - 1);
image_speed = 0.35;
image_alpha = 1;
escape = false;
global.collected = 0;
global.collectsound = mu_entryway_title;
gotowardsPlayer = false;
movespeed = 0;
col = irandom_range(1, 5);
