obj_flowey_battle_final.stage_switch = 0;
instance_destroy(obj_flowey_battle_organic_bloodcell_spawner);
instance_destroy(obj_flowey_battle_organic_virus_spawner);
instance_destroy(obj_flowey_battle_phase_2_organic_virus);
