var cam_width = camera_get_view_width(view_camera[0]);
var cam_height = camera_get_view_height(view_camera[0]);
depth = -25;
sucrose_lighting = false;
sucrose_color = 7490854;
sucrose_color_array = [par_follower, obj_baddiespawner, par_collect, obj_rocketdud, obj_dashpad, obj_gigacherrydead, obj_chocofrog, par_logicobjects];
bloodsauce_lighting = false;
bloodsauce_color = c_black;
bloodsauce_color_array = [par_follower, obj_baddiespawner, par_collect, obj_rocketdud, obj_dashpad, obj_gigacherrydead, obj_chocofrog, par_logicobjects];
stormy_lighting = false;
stormy_color = c_black;
dance_lighting = false;
dance_palette = 0;
sucrose_surface = surface_create(cam_width, cam_height);
surface_set_target(sucrose_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
bloodsauce_surface = surface_create(cam_width, cam_height);
surface_set_target(bloodsauce_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
stormy_surface = surface_create(cam_width, cam_height);
surface_set_target(stormy_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
harry_surface = surface_create(cam_width, cam_height);
surface_set_target(harry_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
dance_surface = surface_create(cam_width, cam_height);
surface_set_target(dance_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
boss_surface = surface_create(cam_width, cam_height);
surface_set_target(boss_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
boss_radius = 120;
radius_increase = 0;