scr_collision_init();
hsp = 1;
vsp = 0;
grav = 0.5;
grounded = 0;
state = 3;
offsetx = random_range(-20, 20);
offsety = random_range(-20, 20);
dir = choose(-1, 1);
pointdraintimer = 100;
sourbuddytype = irandom_range(1, 6);
sourbuddyattachspr = obj_player.spr_machpunch2;
sourbuddydeadspr = obj_player.spr_machpunch2;
sourbuddywalkspr = obj_player.spr_machpunch2;
shakex = 0;
shakemag = 0;
shake_delay = 0;
movespeed = random_range(1, 5);
accel = random_range(0.25, 0.5);
palcolor = random_range(0, 5);
depth = -100;
scr_sourbuddychar();
