ini_open("Options.ini");
global.default_group_gain = ini_read_real("Audio", "master volume", 1);
audio_master_gain(global.default_group_gain);
global.music_group_gain = ini_read_real("Audio", "music volume", 1);
audio_group_set_gain(mu_credits, global.music_group_gain, 0);
global.sfx_group_gain = ini_read_real("Audio", "sfx volume", 1);
audio_group_set_gain(mu_boogiewoogie, global.sfx_group_gain, 0);
global.AntiA = ini_read_real("Video", "AA", false);
global.VSyncon = ini_read_real("Video", "vsync", false);
display_reset(global.AntiA, global.VSyncon);
global.fullscreen = ini_read_real("Video", "fullscreen", false);
window_set_fullscreen(global.fullscreen);
global.GUIon = ini_read_real("Video", "gui", true);
global.mGUI = ini_read_real("Video", "minimalgui", false);
global.timeron = ini_read_real("Game", "timeron", false);
global.timer = ini_read_string("Game", "timer", "2:00");
global.stocks = ini_read_real("Game", "stocks", 4);
global.hazards = ini_read_real("Game", "hazards", 1);
global.Recorddemrec = ini_read_real("Developer", "demrec", false);
global.Devconsole = ini_read_real("Developer", "console", false);
global.frogger = ini_read_real("Developer", "frogger", false);
global.remix = ini_read_real("Developer", "remix", true);
global.buttonrgb1 = ini_read_real("Demrec", "style1", 46);
global.buttonrgb2 = ini_read_real("Demrec", "style2", 49);
global.buttonrgb3 = ini_read_real("Demrec", "style3", 146);
global.hotsaving = ini_read_real("Demrec", "hotsaving", false);
global.shaker = ini_read_real("Video", "shaker", 1);
Scr_PlayerVars();
Scr_Player2Vars();
ini_close();
ini_open("arcade.ini");
global.doiseun = ini_read_real("Characters", "doise", false);
global.pephs = ini_read_real("highscores", "pep", 0);
global.noisehs = ini_read_real("highscores", "noise", 0);
global.vigihs = ini_read_real("highscores", "vigi", 0);
global.fakepephs = ini_read_real("highscores", "fakepep", 0);
global.doisehs = ini_read_real("highscores", "doise", 0);
ini_close();
dontdoshit = false;
savematch = false;
dirty = false;
saveiconalpha = 0;
showicon = false;
icon_index = 0;
depth = -10000;
afterarcade = false;
