event_inherited();
depth = -5;
var bn = "battles.ruinedknights.ballard.";
normalSprite = spr_rkb_ballard;
hurtSprite = spr_rkb_ballard;
dustFilename = "rhkb";
name = dxd_raw(bn + "name");
image_speed = 0.18;
image_xscale = 2;
image_yscale = 2;
xstart = x;
ystart = y;
bt_add_act(bn, "act0");
bt_add_act(bn, "act1");
bt_add_act(bn, "act2");
maxHp = 70;
hp = maxHp;
defense = 5;
baseDefense = defense;
xpReward = 6;
goldReward = 3;
attack = 4;
fullMercyResist = true;
isFleeAvailable = false;
flavorColor = make_color_rgb(55, 113, 221);

if (global.flavor_sprites)
    image_blend = flavorColor;

killcounter = 0;
justkill = false;
vencourage = 0;
vdoneencourage = 0;
vdidencourage = false;
vstare = 0;
vdidstare = false;
vsandwich = false;
siner = 2.0943951023931953;
wingsiner = 0;
stopmove = 5;
