draw_rectangle_color(0, 0, 960, 540, c_black, c_black, c_black, c_black, 0)
draw_set_font(global.bigfont)
draw_set_halign(fa_center)
var _os = optionselected
var as_s = (_os == 0 ? 1 : 0.5)
draw_set_color(c_white)
draw_text_colour(480, 25, "ATTACK STYLE", c_white, c_white, c_white, c_white, as_s)
draw_text_colour(480, 65, attack_ary[attackstyle], c_white, c_white, c_white, c_white, as_s)
var hm_s = (_os == 1 ? 1 : 0.5)
draw_text_colour(480, 100, "HARDMODE", c_white, c_white, c_white, c_white, hm_s)
draw_text_colour(380, 140, "ON", c_white, c_white, c_white, c_white, (hardmode ? 1 : 0.5))
draw_text_colour(580, 140, "OFF", c_white, c_white, c_white, c_white, ((!hardmode) ? 1 : 0.5))
var de_s = (_os == 2 ? 1 : 0.5)
draw_text_colour(480, 175, "MORE ENEMIES", c_white, c_white, c_white, c_white, de_s)
draw_text_colour(380, 215, "ON", c_white, c_white, c_white, c_white, (doubleenem ? 1 : 0.5))
draw_text_colour(580, 215, "OFF", c_white, c_white, c_white, c_white, ((!doubleenem) ? 1 : 0.5))
var sh_s = (_os == 3 ? 1 : 0.5)
draw_text_colour(480, 250, "SUPER MEGA PIZZELLE GAMER VTUBER HUD ", c_white, c_white, c_white, c_white, sh_s)
draw_text_colour(380, 290, "ON", c_white, c_white, c_white, c_white, (badHud ? 1 : 0.5))
draw_text_colour(580, 290, "OFF", c_white, c_white, c_white, c_white, ((!badHud) ? 1 : 0.5))
var tc_s = (_os == 4 ? 1 : 0.5)
draw_text_colour(480, 325, "COLLISIONS", c_white, c_white, c_white, c_white, tc_s)
draw_text_colour(380, 365, "ON", c_white, c_white, c_white, c_white, (collisions ? 1 : 0.5))
draw_text_colour(580, 365, "OFF", c_white, c_white, c_white, c_white, ((!collisions) ? 1 : 0.5))
lp_s = (_os == 5 ? 1 : 0.5)
draw_text_colour(480, 400, "PERFORMANCE MODE", c_white, c_white, c_white, c_white, lp_s)
draw_text_colour(380, 440, "ON", c_white, c_white, c_white, c_white, (lowperf ? 1 : 0.5))
draw_text_colour(580, 440, "OFF", c_white, c_white, c_white, c_white, ((!lowperf) ? 1 : 0.5))
