event_inherited();
depth = -5;
journalId = 3;
var bn = "battles.froggit.";
normalSprite = spr_froglook;
hurtSprite = spr_frogdamage;
dustFilename = "rh_f";
name = dxd_raw(bn + "name");
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
bt_add_act(bn, "act0");
bt_add_act(bn, "act1");
bt_add_act(bn, "act2");
maxHp = 30;
hp = maxHp;
defense = 4;
attack = 4;
xpReward = 3;
goldReward = 2;
mercyResistance = 20;
flavorColor = make_color_rgb(82 + (irandom(15) + choose(-1, 1)), 222 + (irandom(15) + choose(-1, 1)), 119 + (irandom(15) + choose(-1, 1)));
image_blend = global.flavor_sprites ? flavorColor : c_white;
head = instance_create(obj_frog_head);
vencourage = false;
vsmooch = false;
doReturnAnim = false;
attackType = -1;
attackTime = 0;
frogs = 0;
noWhimsun = false;
loox = false;
attackIntense = false;
tongueAnim = 0;
tongue = -4;
tongueTargetObj = -4;
tongueStretchMax = 0;
