image_speed = 0
depth = 8
spriteDoorDefault = spr_leveldoors
spriteDoorUnlocked = spr_doorvisited
spriteDoorLocked = spr_doorblocked
spriteDoorEscape = spr_doorblocked
spriteDoorLight = spr_doorlight
spriteDoorLock = spr_null
lightIndex = irandom_range(0, sprite_get_number(spriteDoorLight) - 1)
