event_inherited();
spriteLeft = spr_flowey_left;
spriteRight = spr_flowey_right;
spriteUp = spr_flowey_up;
rises = 0;
riseTriggered = false;
visible = false;
lookDirection = 4;
overrideNonTalk = true;
funny = false;
dist = 120;
specialMode = false;
destroySpecial = true;
resumeSceneSpecial = false;
