scr_initinput();
scr_collision_init();
depth = -7;
fall = 0;
xH = 0;
yH = 0;
spr_palette = spr_null;
paletteselect = obj_player1.paletteselect;
effectappear = 0;
cantpunch = 0;
character = "P";
grounded = false;
spritereal = spr_danikyo;
grav = 0.5;
state = 4;
hsp = 0;
vsp = 0;
movespeed = 0;
jumpstop = 0;
input_buffer_jump = 8;
input_attack_buffer = 8;
xscale = 1;
yscale = 1;
angle = 0;
flash = 0;
move = 0;
xx = 0;
alarm[0] = 60;
