message = "";
global.roommessage = "";
xi = obj_screen.actualWidth / 2;
yi = -50;
showtext = 0;
depth = -8;
draw_set_font(global.smallfont);
draw_set_halign(fa_center);
draw_set_valign(fa_top);
draw_set_color(c_white);
