if (instance_number(object_index) > 1)
{
    instance_destroy()
    return;
}
scr_playersound_init()
fishDir = 0
move_h = 0
move_v = 0
secret_array = []
jetpackdash = 0
flamecloud_buffer = 0
steppybuffer = 0
rankpos_x = x
rankpos_y = y
transformationlives = 0
punch_afterimage = 0
superchargecombo_buffer = -1
superattackstate = (2 << 0)
afterimagedebris_buffer = 0
scale_xs = 1
scale_ys = 1
verticalbuffer = 0
verticalstate = (2 << 0)
grabclimbbuffer = 0
webID = -4
float = 0
boxxedpepjump = 10
boxxedpepjumpmax = 10
icemovespeed = 0
prevmove = 0
prevhsp = 0
prevstate = (2 << 0)
prevxscale = 1
prevsprite = sprite_index
move = 0
prevmovespeed = 0
previcemovespeed = 0
icedir = 1
icemomentum = 0
savedicedir = 1
ispeppino = false
isgustavo = 0
jumped = 1
grav = 0.5
hsp = 0
vsp = 0
vsp_carry = 0
hsp_carry = 0
rocketvsp = 0
sticking = 0
platformid = -4
xscale = 1
yscale = 1
facehurt = 0
steppy = 0
depth = -7
bubbleBufferMax = irandom_range(25, 50)
bubbleBuffer = 0
movespeed = 19
jumpstop = 0
ramp = 0
ramp_points = 0
bombup_dir = 1
knightmomentum = 0
grabbingenemy = 0
spinsndbuffer = 0
blur_effect = 0
firemouth_dir = 1
firemouth_max = 10
firemouth_buffer = firemouth_max
firemouth_afterimage = 0
cow_buffer = 0
balloonbuffer = 0
shoot_buffer = 0
shoot_max = 20
dynamite_inst = -4
golfid = -4
bombgrabID = -4
barrelslope = 0
barrel_maxmovespeed = 16
barrel_maxfootspeed = 10
barrel_rollspeed_threshold = 10
barrel_accel = 1
barrel_deccel = 1
barrel_slopeaccel = 0.25
barrel_slopedeccel = 0.5
barrelroll_slopeaccel = 0.5
barrelroll_slopedeccel = 0.35
coyote_time = 0
can_jump = false
hurt_buffer = -1
hurt_max = 120
invhurt_buffer = 0
invhurt_max = 30
ratmount_movespeed = 8
ratmount_fallingspeed = 0
ratgrabbedID = -4
ratpowerup = -4
ratshootbuffer = 0
rateaten = 0
gustavodash = 0
brick = 0
ratmountpunchtimer = 25
gustavokicktimer = 5
cheesepep_buffer = 0
cheesepep_max = 10
pepperman_accel = 0.25
pepperman_deccel = 0.5
pepperman_accel_air = 0.15
pepperman_deccel_air = 0.25
pepperman_maxhsp_normal = 6
pepperman_jumpspeed = 11
pepperman_grabID = -4
shoulderbash_mspeed_start = 12
shoulderbash_mspeed_loop = 10
shoulderbash_jumpspeed = 11
visible = true
state = (20 << 0)
jumpAnim = 1
landAnim = 0
machslideAnim = 0
moveAnim = 1
stopAnim = 1
crouchslideAnim = 1
crouchAnim = 1
machhitAnim = 0
stompAnim = 0
inv_frames = 0
hurted = 0
autodash = 0
mach2 = 0
stop_buffer = 8
slope_buffer = 8
stop_max = 16
parry = 0
parry_inst = -4
taunt_to_parry_max = 10
parry_count = 0
parry_max = 8
is_firing = 0
input_buffer_jump = 8
input_buffer_secondjump = 8
input_buffer_highjump = 8
input_buffer_walljump = 0
input_buffer_slap = 8
input_attack_buffer = 0
input_finisher_buffer = 0
input_up_buffer = 0
input_down_buffer = 0
hit_connected = 0
player_x = x
player_y = y
targetRoom = rm_missing
targetDoor = "A"
flash = 0
key_particles = 0
barrel = 0
bounce = 0
a = 0
idle = 0
attacking = 0
slamming = 0
superslam = 0
grounded = true
grinding = 0
machpunchAnim = 0
punch = 0
machfreefall = 0
shoot = 0
instakillmove = 0
stunmove = 0
windingAnim = 0
facestompAnim = 0
ladderbuffer = 0
toomuchalarm1 = 0
toomuchalarm2 = 0
idleanim = 0
momemtum = 0
cutscene = 0
grabbing = 0
dir = xscale
shotgunAnim = 0
goingdownslope = 0
goingupslope = 0
fallinganimation = 0
bombpeptimer = 100
suplexmove = 0
suplexhavetomash = 0
anger = 0
angry = 0
baddiegrabbedID = 0
spr_palette = spr_peppalette
character = "P"
scr_characterspr()
paletteselect = 1
colorchange = 0
treasure_x = 0
treasure_y = 0
treasure_room = 0
wallspeed = 0
tauntstoredstate = (2 << 0)
tauntstoredmovespeed = 6
tauntstoredsprite = spr_null
taunttimer = 20
tauntstoredvsp = 0
tauntstoredisgustavo = 0
tube_id = -1
backtohubstartx = x
backtohubstarty = y
backtohubroom = 0
slapcharge = 0
slaphand = 1
slapbuffer = 8
slapflash = 0
freefallsmash = 0
costumercutscenetimer = 0
heavy = 0
lastroom_x = 0
lastroom_y = 0
lastroom = 0
lastTargetoor = "A"
hallway = 0
savedhallway = 0
hallwaydirection = 0
savedhallwaydirection = 0
vhallwaydirection = 0
savedvhallwaydirection = 0
verticalhallway = 0
savedverticalhallway = 0
vertical_x = x
verticalhall_vsp = 0
box = 0
roomstartx = 0
roomstarty = 0
swingdingbuffer = 0
swingdingdash = 0
lastmove = 0
backupweapon = 0
stickpressed = 0
spotlight = 1
macheffect = 0
chargeeffectid = obj_null
dashcloudid = obj_null
crazyruneffectid = obj_null
fightball = 0
superslameffectid = obj_null
speedlineseffectid = obj_null
angryeffectid = obj_null
thrown = false
mach1snd = -1
mach2snd = -1
mach3snd = -1
knightslide = -1
bombpep1snd = -1
mach4snd = -1
tumble2snd = -1
tumble1snd = -1
tumble3snd = -1
rocketsnd = -1
pogospeed = 2
pogocharge = 100
pogochargeactive = 0
wallclingcooldown = 10
bombcharge = 0
flashflicker = 0
flashflickertime = 0
kickbomb = 0
doublejump = 0
pogospeedprev = 0
fightballadvantage = 0
coopdelay = 0
supercharged = 0
superchargedeffectid = obj_null
used_supercharge = 0
pizzashield = 0
pizzashieldid = obj_null
pizzapepper = 0
transformation[0] = (53 << 0)
transformation[1] = (49 << 0)
transformation[2] = (40 << 0)
transformation[3] = (35 << 0)
transformation[4] = (23 << 0)
transformation[5] = (26 << 0)
transformation[6] = (27 << 0)
transformation[7] = (32 << 0)
transformation[8] = (31 << 0)
transformation[9] = (12 << 0)
transformation[10] = (11 << 0)
transformation[11] = (61 << 0)
transformation[12] = (33 << 0)
transformation[13] = (91 << 0)
transformation[14] = (114 << 0)
transformation[15] = (18 << 0)
transformation[16] = (19 << 0)
transformation[17] = (13 << 0)
transformation[18] = (152 << 0)
transformation[19] = (148 << 0)
transformation[20] = (186 << 0)
transformation[21] = (188 << 0)
transformation[22] = (54 << 0)
transformation[23] = (55 << 0)
transformation[24] = (56 << 0)
transformation[25] = (118 << 0)
transformation[26] = (116 << 0)
transformation[27] = (115 << 0)
transformation[28] = (24 << 0)
transformation[29] = (34 << 0)
transformation[30] = (51 << 0)
transformation[31] = (50 << 0)
transformation[32] = (15 << 0)
transformation[33] = (16 << 0)
transformation[34] = (14 << 0)
transformation[35] = (37 << 0)
transformation[36] = (36 << 0)
transformation[37] = (187 << 0)
transformation[38] = (271 << 0)
transformation[39] = (272 << 0)
transformation[40] = (270 << 0)
transformation[41] = (273 << 0)
c = 0
stallblock = 0
breakdance = 50
skateboarding = 0
drownBuffer = 0
drownBufferMax = 250
hitX = x
hitY = y
hithsp = 0
hitvsp = 0
hitstunned = 0
hitxscale = 1
stunned = 0
hitLag = 25
supercharge = 0
mort = 0
sjumpvsp = -12
freefallvsp = 15
hitlist = ds_list_create()
animlist = ds_list_create()
lungeattackID = -4
lunge_hits = 0
lunge_hit_buffer = 0
lunge_buffer = 0
finisher = 0
finisher_buffer = 0
finisher_hits = 0
uplaunch = 0
downlaunch = 0
dash_doubletap = 0
finishingblow = 0
launch = 0
launched = 1
launch_buffer = 0
jetpackfuel = 0
jetpackmax = 200
walljumpbuffer = 0
farmerpos = 0
clowntimer = 0
knightmiddairstop = 0
knightmove = -1
fishthrown = false
wet = false
angle = 0
mach4mode = 0
railmomentum = 0
railmovespeed = 0
raildir = 1
boxxed = 0
boxxeddash = 0
cheesepeptimer = -1
cheeseballbounce = 0
slopejump = 0
slopejumpx = 0
hooked = 0
swingdingendcooldown = 0
crouchslipbuffer = 0
breakdance_speed = 0.25
notecreate = 50
jetpackbounce = 0
firemovedir = 0
ladderfast = 0
backtohubbuffer = 0
fishlandtimer = 600
in_supertaunt = false
cutscene_frame = -1

// HACK: fmod sucks.

sjumpprep = false;

// HACK: are you fucking kidding me

sjumped = false;
