box = 3154;
create_count = 0;
create_max = 8;
create_alarm = 35;
end_alarm = 20;
can_end = false;
no_loop_end = false;
silv_speed = 3;
silv_distance = silv_speed * 40;
silv_sign = choose(-1, 1);
event_user(0);
