audio_sound_pitch(snd_txtSock, 0.9);
op.twaitFunc = -1;
op.twaitFunc2 = -1;
op.drawBox = true;
des(oMiniFace);
depth = -15000;
use_text[0] = "Big Burger";
use_x[0] = 200;
use_y[0] = 200;
use_font[0] = sFont1;
use_rgb[0] = 16777215;
use_voice[0] = 0;
use_printSeed[0] = [];
use_function[0] = -1;
funcEnd = -1;
use_bXscale[0] = 2;
use_bYscale[0] = 2;
obj_seed[0] = "0";
in = 0;
spell = "";
voiceTy = 0;
sp = 0;
letters_allow = 0;
rowCount = 0;
res_keys();
ty = 0;
noVoice = [" ", "^", "!", ".", "?", ",", ":", "/", "\\", "|", "*", "€", "@", "£", "_"];
voiceDelay = 1;
split = [];
useText = "";
useLnegth = 0;
useC = 0;
waitZ = 2;
shakeHeadTime = 0;
shakeHeadPos = [0, 0];
