text_effect = "twitchy";
attack = false;
message[0] = "My love...";
message[1] = "My child...";
message[2] = "All... gone.";
message[3] = "Why wouldn't you#just...";
message_end = 3;
message_current = 0;
message_draw = "";
increase = global.text_speed;
characters = 0;
hold = 0;
message_length = string_length(message[message_current]);
script_execute(scr_generate_text_counters);
circle_text_angle = global.circle_text_angle_default;
circle_text_angle_direction = 1;
