event_inherited();
up_sprite = spr_geno_alphys_up_talk;
right_sprite = spr_geno_alphys_left_walk;
down_sprite = spr_geno_alphys_up_talk;
left_sprite = spr_geno_alphys_left_walk;
up_sprite_idle = spr_geno_alphys_up_talk;
right_sprite_idle = spr_geno_alphys_right_talk;
down_sprite_idle = spr_geno_alphys_up_talk;
left_sprite_idle = spr_geno_alphys_left_talk;
action_sprite = false;
scene = 0;
x_dest[0] = x;
y_dest[0] = y;
actor_speed = 3;
axis_override = "nothing";
end_direction = "left";
walk_collider = -4;
npc_voice_sfx = snd_talk_alphys;
