if (live_call())
    return global.live_result;

credits_entry[0][0] = "Project Lead:";
credits_entry[0][1] = "MasterSwordRemix";
credits_entry[1][0] = "Programming:";
credits_entry[1][1] = "Spasco";
credits_entry[1][2] = "Deadkat";
credits_entry[1][3] = "Mysteryracer";
credits_entry[2][0] = "Narrative Design:";
credits_entry[2][1] = "MasterSwordRemix";
credits_entry[2][2] = "AWildDayDreamer";
credits_entry[2][3] = "Pippy V.";
credits_entry[3][0] = "Dialogue:";
credits_entry[3][1] = "MasterSwordRemix";
credits_entry[3][2] = "Pippy V.";
credits_entry[4][0] = "Concept Art:";
credits_entry[4][1] = "Figburn";
credits_entry[4][2] = "GlitchedPie";
credits_entry[4][3] = "TeleviQ";
credits_entry[4][4] = "Nerosensei";
credits_entry[4][5] = "Gaziter";
credits_entry[4][6] = "InkuNoodle";
credits_entry[4][7] = "Noteblock";
credits_entry[4][8] = "AeroArtwork";
credits_entry[5][0] = "Additional Concepts:";
credits_entry[5][1] = "MarshieMonarch";
credits_entry[5][2] = "Greeli_";
credits_entry[5][3] = "AWildDaydreamer";
credits_entry[5][4] = "Grey Duovis";
credits_entry[5][5] = "LitvacArt";
credits_entry[5][6] = "Emmalume";
credits_entry[5][7] = "Sweaterbat";
credits_entry[5][8] = "StillLiam";
credits_entry[6][0] = "Room & Level Design:";
credits_entry[6][1] = "MasterSwordRemix";
credits_entry[6][2] = "Figburn";
credits_entry[6][3] = "Glitchedpie";
credits_entry[6][4] = "AWildDaydreamer";
credits_entry[7][0] = "Spritework:";
credits_entry[7][1] = "Figburn";
credits_entry[7][2] = "GlitchedPie";
credits_entry[7][3] = "Deadkat";
credits_entry[7][4] = "Gaziter";
credits_entry[7][5] = "AeroArtwork";
credits_entry[8][0] = "Additional Spritework:";
credits_entry[8][1] = "Vegard Jensen";
credits_entry[8][2] = "Barosaros";
credits_entry[8][3] = "Bloquito";
credits_entry[8][4] = "AWildDaydreamer";
credits_entry[8][5] = "TeleviQ";
credits_entry[8][6] = "Kcadbackwards";
credits_entry[9][0] = "'Red' Design:";
credits_entry[9][1] = "Taxiderby";
credits_entry[10][0] = "'Cooper' Design:";
credits_entry[10][1] = "Migs";
credits_entry[11][0] = "'Flower Girls' Design:";
credits_entry[11][1] = "AeroArtwork";
credits_entry[12][0] = "Music:";
credits_entry[12][1] = "MasterSwordRemix";
credits_entry[12][2] = "Noteblock";
credits_entry[12][3] = "MyNewSoundtrack";
credits_entry[12][4] = "Figburn";
credits_entry[13][0] = "Additional Music:";
credits_entry[13][1] = "GlitchedPie";
credits_entry[13][2] = "emBer";
credits_entry[13][3] = "DYLZAL";
credits_entry[13][4] = "Scott Joplin";
credits_entry[14][0] = "Sound Design:";
credits_entry[14][1] = "MasterSwordRemix";
credits_entry[14][2] = "Spasco";
credits_entry[14][3] = "Figburn";
credits_entry[14][4] = "GlitchedPie";
credits_entry[15][0] = "Voice of Mew Mew:";
credits_entry[15][1] = "PhichanVA";
credits_entry[16][0] = "Playtesters:";
credits_entry[16][1] = "Raymes";
credits_entry[16][2] = "Sunsetbyplane";
credits_entry[16][3] = "LeopardBunny";
credits_entry[16][4] = "Evan Smith";
credits_entry[16][5] = "Saltydkdan";
credits_entry[16][6] = "Bubbled-tea-dreams";
credits_entry[16][7] = "Sr. Pelo";
credits_entry[16][8] = "Frigadae";
credits_entry[16][9] = "TheKameru";
credits_entry[16][10] = "Chocohex";
credits_entry[16][11] = "Icewolf";
credits_entry[16][12] = "Doggybag";
credits_entry[16][13] = "Infernocop";
credits_entry[16][14] = "Astratt";
credits_entry[16][15] = "Zarla";
credits_entry[16][16] = "Yamina";
credits_entry[16][17] = "Blumod";
credits_entry[16][18] = "Scoffy";
credits_entry[16][19] = "Coal Bones";
credits_entry[16][20] = "Trent Noah";
credits_entry[16][21] = "Simisear";
credits_entry[16][22] = "Polybius3D";
credits_entry[16][23] = "BeepPerson";
credits_entry[16][24] = "TsunamiCoRyan";
credits_entry[16][25] = "RhenaudTheLukark";
credits_entry[16][26] = "AgentDrako";
credits_entry[16][27] = "Beesecase";
credits_entry[16][28] = "R2d2kx100";
credits_entry[16][29] = "Anonymous_";
credits_entry[16][30] = "PietroPan";
credits_entry[16][31] = "Skost";
credits_entry[16][32] = "Minmo";
credits_entry[16][33] = "CapsuleGravy";
credits_entry[16][34] = "Izzy";
credits_entry[16][35] = "DragnirMK";
credits_entry[17][0] = "Special Thanks:";
credits_entry[17][1] = "Tifapunchface";
credits_entry[17][2] = "Jillian Brodsky";
credits_entry[17][3] = "2XMM2";
credits_entry[17][4] = "Squiish";
credits_entry[17][5] = "SuperSonic7CE";
credits_entry[17][6] = "Radio";
credits_entry[17][7] = "Loaf";
credits_entry[17][8] = "Daynadooodles";
credits_entry[17][9] = "Kenju";
credits_entry[17][10] = "AstroAmphibian";
credits_entry[17][11] = "Blembino";
credits_entry[17][12] = "Anissa Hustins";
credits_entry[17][13] = "Commissioner Tadpole";
credits_entry[17][14] = "Autumn";
credits_entry[17][15] = "Team Switched";
credits_entry[17][16] = "Hobo Nate";
credits_entry[17][17] = "Ronin";
credits_entry[17][18] = "Wolfman98002015";
credits_entry[17][19] = "Angelasamshi";
credits_entry[17][20] = "Fatz";
credits_entry[17][21] = "Norin";
credits_entry[17][22] = "LegitimateNoodle";
credits_entry[17][23] = "Shayy";
credits_entry[17][24] = "VyletBunni";
credits_entry[17][25] = "Easynam";
credits_entry[17][26] = "Nightmargin";
credits_entry[17][27] = "YellowAfterlife";
credits_entry[17][28] = "Guzusuru";
credits_entry[17][29] = "Game Jolt";
credits_entry[17][30] = "And you!";
credits_entry[18][0] = "Not Special - No Thanks:";
credits_entry[18][1] = "The Shufflers";
credits_entry[19][0] = "Based on the world of UNDERTALE,\ncreated by";
credits_entry[19][1] = "";
credits_entry[19][2] = "Toby Fox & Temmie Chang";

for (var i = 0; i < 21; i++)
    credits_entry[20][i] = "";

credits_entry[20][21] = "Thank you for playing!";
x_offset = 200;
y_offset = 240;
y_max = -1;
y_speed = 0;
y_slow_down = false;
slow_down_treshold = 90;
fade_out = false;
flowey_noloop = false;
credits_song = audio_play_sound(mus_flowey_world, 20, 0);
song_length = audio_sound_length(credits_song) * 30;

if (global.hotland_flag[10] == 0)
{
    delay_timer = 0;
}
else
{
    delay_timer = 120;
    audio_play_sound(mus_intronoise, 10, 0);
    audio_stop_sound(credits_song);
}

scene = 0;
cutscene_timer = 0;
draw_alpha = 1;
text_alpha = 1;
camera_target_current = 0;
target_room[0] = 221;
camera_start_x[0] = 260;
camera_start_y[0] = 360;
pan_dir[0] = 135;
target_room[1] = 144;
camera_start_x[1] = 280;
camera_start_y[1] = 220;
pan_dir[1] = 225;
target_room[2] = 127;
camera_start_x[2] = 674;
camera_start_y[2] = 164;
pan_dir[2] = 0;
target_room[3] = 59;
camera_start_x[3] = 430;
camera_start_y[3] = 340;
pan_dir[3] = 45;
target_room[4] = 31;
camera_start_x[4] = 300;
camera_start_y[4] = 340;
pan_dir[4] = 90;
pan_speed = 1/3;
start_delay = 15;
wait_timer = 4;
var room_number = array_length(target_room);
var song_length_wbreaks = song_length - (wait_timer * 30 * room_number) - (start_delay * 30);
room_duration = song_length_wbreaks / room_number;
instance_destroy(obj_radio);

if (global.meta_flowey_fight_count < 3 && global.hotland_flag[10] == 0)
    global.meta_flowey_fight_count += 1;

scr_savegame_meta();

if (file_exists("Save.sav"))
    file_delete("Save.sav");
