event_inherited();
grav = -0.2
hsp = 0
vsp = 0
movespeed = 1
state = baddiestate.eyescreamwait
lerpamt = 0.2
substate = 0
targety  = 0
randomx = irandom_range(50, 100)
randomy = irandom_range(100, 200)
timer = irandom_range(60, 180)
cancollide = false;
maxtime = timer
stunned = 0
alarm[0] = 150
roaming = 1
collectdrop = 5
flying = 0
straightthrow = 0
cigar = 0
cigarcreate = 0
stomped = 0
shot = 0
thrown = 0
reset = 0
flash = 0
landspr = spr_gumslime_walk;
idlespr = spr_gumslime_stun;
fallspr = spr_gumslime_walk;
stunfallspr = spr_gumslime_stun;
walkspr = spr_gumslime_walk;
turnspr = spr_gumslime_walk;
recoveryspr = spr_eyescreamsandwich_dead
grabbedspr = spr_eyescreamsandwich_dead
scaredspr = spr_eyescreamsandwich_dead
deadspr = spr_eyescreamsandwich_dead

hp = 10
slapped = 0
grounded = 1
birdcreated = 0
boundbox = 0
idletimer = 200