horigin = x;
vsp = 0
hsp = 0
grav = 0
cigar = 0;
stomped = 0;
spr_palette = pal_harry;
paletteselect = 0;
set_theme = -4
hudx = -400
if (x != obj_player.x)
	image_xscale = -sign(x - obj_player.x);
if x <= obj_player.x
	hudx = global.cam_w + 400
sprite_index = obj_player.spr_gummyharry_dead
