enum states 
{
	normal = 0,
	tumble = 1,
	finishingblow = 2,
	ejected = 3,
	fireass = 4,
	firemouth = 5,
	titlescreen = 6,
	tacklecharge = 7,
	cheeseball = 8,
	cheesepep = 9,
	cheesepepstick = 10,
	boxxedpep = 11,
	climbwall = 12,
	knightpepslopes = 13,
	portal = 14,
	chainsawbump = 15,
	suplexgrab = 16,
	gottreasure = 17,
	knightpep = 18,
	bombpep = 19,
	chainsawpogo = 20,
	stunned = 21,
	chainsaw = 22,
	machroll = 23,
	shotgun = 24,
	superslam = 25,
	skateboard = 26,
	grind = 27,
	grab = 28,
	punch = 29,
	shoulder = 30,
	backbreaker = 31,
	bossintro = 32,
	ejected2 = 33,
	keyget = 34,
	tackle = 35,
	jump = 36,
	ladder = 37,
	slipnslide = 38,
	comingoutdoor = 39,
	sjump = 40,
	victory = 41,
	sjumpprep = 42,
	crouch = 43,
	crouchjump = 44,
	crouchslide = 45,
	mach1 = 46,
	mach2 = 47,
	machslide = 48,
	bump = 49,
	hurt = 50,
	freefall = 51,
	hang = 52,
	freefallland = 53,
	door = 54,
	barrelbounce = 55,
	barrelcrouch = 56,
	barrelfloat = 57,
	barrelmach2 = 58,
	barrelmach1 = 59,
	barrelfall = 60,
	barrelnormal = 61,
	barrelslipnslide = 62,
	barrelroll = 63,
	current = 64,
	boulder = 65,
	mach3 = 66,
	freefallprep = 67,
	sjumpland = 68,
	slapdash = 69,
	parrying = 70,
	breakdance = 71,
	flustered = 72,
	shoulderbash = 73,
	gunshoot = 74,
	shoryuken = 75,
	pipe = 76,
	faceplant = 77,
	ghost = 78,
	golf = 79,
	thok = 80,
	pogo = 81,
	wait = 82,
	handstand = 83,
	sidejumpprep = 84,
	sidejump = 85,
	grow = 86,
	hitstun = 87,
	slipbanan = 88,
	taxi = 89,
	balllol = 90,
	kungfu = 91,
	tackleold = 92,
	gameover = 93,
	timesup = 94,
	ramp = 95,
	weeniemount = 96,
	firemove = 97,
	pitfall = 98,
	heropep = 99,
	homingattack = 100,
	pinch = 101,
	start = 102,
	swingdingfinish = 103,
	seat = 104,
	barrel = 105,
	smallpep = 106,
	smallpepdash = 107,
	retrodeath = 108,
	firework = 109,
	nothing = 110,
	levelselect = 111,
	cheeseslime = 112,
	cheeseslimeattack = 113,
	actor = 114,
	knightpepbump = 115,
	secretportal = 116,
	held = 117,
	lunge = 118,
	kungfugrab = 119,
	nwalljump = 120,
	kingbubble = 121,
	npclocked = 122,
	forcedfall = 123,
	bombknockback = 124,
	hubeject = 125,
	sagelevelentrance = 126,
	gatecutscene = 127,
	noclip = 128,
	noisecrusher = 129,
	
	// kinda odd how its this high
	enemyhitstun = 300,
}

function State(_id, _name, __script, _flags = 0) {
    var inst = {
        __id:     _id,
        name:   _name,
        _script: !is_undefined(__script) ? method(other, __script) : undefined,
        flags:  _flags
    };
    other.statemachine[_id] = inst;
    return inst;
}

function scr_definestates()
{
    State(states.normal, "Normal", scr_player_normal);
    State(states.tumble, "Tumble", scr_player_tumble);
    State(states.finishingblow, "FinishingBlow", scr_player_finishingblow);
    State(states.ejected, "Ejected", scr_player_ejected);
    State(states.fireass, "Fireass", scr_player_fireass);
    State(states.firemouth, "Firemouth", scr_player_firemouth);
    State(states.titlescreen, "Titlescreen", scr_player_titlescreen);
    State(states.tacklecharge, "TackleCharge", scr_player_tacklecharge);
    State(states.cheeseball, "Cheeseball", scr_player_cheeseball);
    State(states.cheesepep, "CheesePep", scr_player_cheesepep);
    State(states.cheesepepstick, "CheesePepStick", scr_player_cheesepepstick);
    State(states.boxxedpep, "BoxxedPep", scr_player_boxxedpep);
    State(states.climbwall, "ClimbWall", scr_player_climbwall);
    State(states.knightpepslopes, "KnightPepSlopes", scr_player_knightpepslopes);
    State(states.portal, "Portal", scr_player_portal);
    State(states.chainsawbump, "ChainsawBump", scr_player_chainsawbump);
    State(states.suplexgrab, "SuplexGrab", scr_player_suplexgrab);
    State(states.gottreasure, "GotTreasure", scr_player_gottreasure);
    State(states.knightpep, "KnightPep", scr_player_knightpep);
    State(states.bombpep, "BombPep", scr_player_bombpep);
    State(states.chainsawpogo, "ChainsawPogo", scr_player_chainsawpogo);
    State(states.stunned, "Stunned", scr_player_stunned);
    State(states.chainsaw, "Chainsaw", scr_player_chainsaw);
    State(states.machroll, "MachRoll", scr_player_machroll);
    State(states.shotgun, "Shotgun", scr_player_shotgun);
    State(states.superslam, "SuperSlam", scr_player_superslam);
    State(states.skateboard, "Skateboard", scr_player_skateboard);
    State(states.grind, "Grind", scr_player_grind);
    State(states.grab, "Grab", scr_player_grab);
    State(states.punch, "Punch", scr_player_punch);
    State(states.shoulder, "Shoulder", scr_player_shoulder);
    State(states.backbreaker, "Backbreaker", scr_player_backbreaker);
    State(states.bossintro, "BossIntro", scr_player_bossintro);
    State(states.ejected2, "Ejected2", scr_player_ejected);
    State(states.keyget, "KeyGet", scr_player_keyget);
    State(states.tackle, "Tackle", scr_player_tackle);
    State(states.jump, "Jump", scr_player_jump);
    State(states.ladder, "Ladder", scr_player_ladder);
    State(states.slipnslide, "SlipNSlide", scr_player_slipnslide);
    State(states.comingoutdoor, "ComingOutDoor", scr_player_comingoutdoor);
    State(states.sjump, "SJump", scr_player_Sjump);
    State(states.victory, "Victory", scr_player_victory);
    State(states.sjumpprep, "SJumpPrep", scr_player_Sjumpprep);
    State(states.crouch, "Crouch", scr_player_crouch);
    State(states.crouchjump, "CrouchJump", scr_player_crouchjump);
    State(states.crouchslide, "CrouchSlide", scr_player_crouchslide);
    State(states.mach1, "Mach1", scr_player_mach1);
    State(states.mach2, "Mach2", scr_player_mach2);
    State(states.machslide, "MachSlide", scr_player_machslide);
    State(states.bump, "Bump", scr_player_bump);
    State(states.hurt, "Hurt", scr_player_hurt);
    State(states.freefall, "FreeFall", scr_player_freefall);
    State(states.hang, "Hang", scr_player_hang);
    State(states.freefallland, "FreeFallLand", scr_player_freefallland);
    State(states.door, "Door", scr_player_door);
    State(states.barrelbounce, "BarrelBounce", scr_player_barrelbounce);
    State(states.barrelcrouch, "BarrelCrouch", scr_player_barrelcrouch);
    State(states.barrelfloat, "BarrelFloat", scr_player_barrelfloat);
    State(states.barrelmach2, "BarrelMach2", scr_player_barrelmach2);
    State(states.barrelmach1, "BarrelMach1", scr_player_barrelmach1);
    State(states.barrelfall, "BarrelFall", scr_player_barrelfall);
    State(states.barrelnormal, "BarrelNormal", scr_player_barrelnormal);
    State(states.barrelslipnslide, "BarrelSlipNSlide", scr_player_barrelslipnslide);
    State(states.barrelroll, "BarrelRoll", scr_player_barrelroll);
    State(states.current, "Current", scr_player_current);
    State(states.boulder, "Boulder", scr_player_boulder);
    State(states.mach3, "Mach3", scr_player_mach3);
    State(states.freefallprep, "FreeFallPrep", scr_player_freefallprep);
    State(states.sjumpland, "SJumpLand", scr_player_Sjumpland);
    State(states.slapdash, "SlapDash", scr_player_slapdash);
    State(states.parrying, "Parry", scr_player_parry);
    State(states.breakdance, "Breakdance", scr_player_breakdance);
    State(states.flustered, "Flustered", scr_player_flustered);
    State(states.shoulderbash, "Shoulderbash", scr_player_shoulderbash);
    State(states.gunshoot, "GunShoot", scr_player_gunshoot);
    State(states.shoryuken, "Shoryuken", scr_player_shoryuken);
    State(states.pipe, "Pipe", scr_player_pipe);
    State(states.faceplant, "Faceplant", scr_player_faceplant);
    State(states.ghost, "Ghost", scr_player_ghost);
    State(states.golf, "Golf", scr_player_golf);
    State(states.thok, "Thok", scr_player_thok);
    State(states.pogo, "Pogo", scr_player_pogo);
    State(states.wait, "Wait", scr_player_wait);
    State(states.handstand, "Handstand", scr_player_handstand);
    State(states.sidejumpprep, "SideJumpPrep", scr_player_sidejumpprep);
    State(states.sidejump, "SideJump", scr_player_sidejump);
    State(states.grow, "Grow", scr_player_grow);
    State(states.hitstun, "Hitstun", scr_player_hitstun, 1);
    State(states.slipbanan, "SlipBanan", scr_player_slipbanan);
    State(states.taxi, "Taxi", scr_player_taxi);
    State(states.balllol, "BallLOL", scr_player_balllol);
    State(states.kungfu, "KungFu", scr_player_kungfu);
    State(states.tackleold, "TackleOLD", scr_player_tackleold);
    State(states.gameover, "GameOver", scr_player_gameover);
    State(states.timesup, "TimesUp!", scr_player_timesup);
    State(states.ramp, "Ramp", scr_player_ramp);
    State(states.weeniemount, "WeenieMount", scr_player_weeniemount);
    State(states.firemove, "FireMove", scr_player_firemove);
    State(states.pitfall, "PitFall", scr_player_pitfall);
    State(states.heropep, "HeroPep", scr_player_heropep);
    State(states.homingattack, "HomingAttack", scr_playerS_homingattack);
    State(states.pinch, "Pinch", scr_player_pinch);
    State(states.start, "Start", scr_player_start);
    State(states.swingdingfinish, "SwingDingFinish", scr_player_swingdingfinish);
    State(states.seat, "Seat", scr_player_seat);
    State(states.barrel, "Barrel", scr_player_barrel);
    State(states.smallpep, "SmallPep", scr_player_smallpep);
    State(states.smallpepdash, "SmallPepDash", scr_player_smallpepdash);
    State(states.retrodeath, "#RETRODeath", scr_player_RETROdeath);
    State(states.firework, "Firework", scr_player_firework);
    State(states.nothing, "Nothing...", undefined);
    State(states.levelselect, "LevelSelect", scr_player_levelselect);
    State(states.cheeseslime, "Cheeseslime", scr_playerC_normal);
    State(states.cheeseslimeattack, "CheeseslimeAttack", scr_playerC_attack);
    State(states.actor, "Actor", scr_player_actor);
    State(states.knightpepbump, "KnightPepBump", scr_player_knightpepbump);
    State(states.secretportal, "SecretPortal", undefined);
    State(states.held, "Held", scr_player_held);
    State(states.lunge, "Lunge", scr_player_lunge);
    State(states.kungfugrab, "KungFuGrab", scr_player_kungfugrab);
    State(states.nwalljump, "NWallJump", scr_playerN_walljump);
    State(states.kingbubble, "KingBubble", scr_player_kingbubble);
    State(states.npclocked, "NPCLocked", scr_player_npclocked);
    State(states.forcedfall, "ForcedFall", scr_player_forcedfall);
    State(states.bombknockback, "BombKnockback", scr_player_bombknockback);
    State(states.hubeject, "HubEject", scr_player_hubeject);
    State(states.sagelevelentrance, "SageLevelEntrance", scr_player_sagelevelentrance);
    State(states.gatecutscene, "GateCutscene", scr_player_gatecutscene);
    State(states.noclip, "NoClip", scr_player_noclip);
    //State(states.noisecrusher, "NoiseCrusher", scr_player_noisecrusher);
}
