depth = -room_height - 1;
image_speed = 0;
image_index = 0;
disjoint_default_x = x - obj_author_torso_shop.x;
disjoint_default_y = y - obj_author_torso_shop.y;
disjoint_x = 0;
disjoint_y = 0;
can_talk_no_loop = false;
head_sprite = spr_author_head_normal_new_shop;
