gml_pragma("global", @'global.__ggpo_string_buffer = undefined')
gml_pragma("global", @'__init_action()')
gml_pragma("global", @'__init_global()')
gml_pragma("global", @'__global_object_depths()')
gml_pragma("global", @'global.__gameframe_buffer = undefined')
