line_offset = 0;
line_length = 250;
dash_length = 10;
gap_length = 6;
line_segments = line_length / (dash_length + gap_length);
x_start[line_segments] = 0;
y_start[line_segments] = 0;
x_target = 0;
y_target = 0;
