instance_destroy(obj_battle_enemy_attack_jandroid_garbage_can);
instance_destroy(obj_battle_enemy_attack_jandroid_garbage);
instance_destroy(obj_battle_enemy_attack_jandroid_slippery_floor_warning);
instance_destroy(obj_battle_enemy_attack_goosic_disk);
instance_destroy(obj_battle_enemy_attack_jandroid_soap_collider);

with (obj_dialogue_box_battle_transformation_any)
    event_user(0);
