function State(_id, _name, __script, _flags = 0) {
    var inst = {
        __id:     _id,
        name:   _name,
        _script: !is_undefined(__script) ? method(other, __script) : undefined,
        flags:  _flags
    };
    other.statemachine[_id] = inst;
    return inst;
}

function scr_definestates()
{
    State(0, "Normal", scr_player_normal);
    State(1, "Tumble", scr_player_tumble);
    State(2, "FinishingBlow", scr_player_finishingblow);
    State(3, "Ejected", scr_player_ejected);
    State(4, "Fireass", scr_player_fireass);
    State(5, "Firemouth", scr_player_firemouth);
    State(6, "Titlescreen", scr_player_titlescreen);
    State(7, "TackleCharge", scr_player_tacklecharge);
    State(8, "Cheeseball", scr_player_cheeseball);
    State(9, "CheesePep", scr_player_cheesepep);
    State(10, "CheesePepStick", scr_player_cheesepepstick);
    State(11, "BoxxedPep", scr_player_boxxedpep);
    State(12, "ClimbWall", scr_player_climbwall);
    State(13, "KnightPepSlopes", scr_player_knightpepslopes);
    State(14, "Portal", scr_player_portal);
    State(15, "ChainsawBump", scr_player_chainsawbump);
    State(16, "SuplexGrab", scr_player_suplexgrab);
    State(17, "GotTreasure", scr_player_gottreasure);
    State(18, "KnightPep", scr_player_knightpep);
    State(19, "BombPep", scr_player_bombpep);
    State(20, "ChainsawPogo", scr_player_chainsawpogo);
    State(21, "Stunned", scr_player_stunned);
    State(22, "Chainsaw", scr_player_chainsaw);
    State(23, "MachRoll", scr_player_machroll);
    State(24, "Shotgun", scr_player_shotgun);
    State(25, "SuperSlam", scr_player_superslam);
    State(26, "Skateboard", scr_player_skateboard);
    State(27, "Grind", scr_player_grind);
    State(28, "Grab", scr_player_grab);
    State(29, "Punch", scr_player_punch);
    State(30, "Shoulder", scr_player_shoulder);
    State(31, "Backbreaker", scr_player_backbreaker);
    State(32, "BossIntro", scr_player_bossintro);
    State(33, "Ejected2", scr_player_ejected);
    State(34, "KeyGet", scr_player_keyget);
    State(35, "Tackle", scr_player_tackle);
    State(36, "Jump", scr_player_jump);
    State(37, "Ladder", scr_player_ladder);
    State(38, "SlipNSlide", scr_player_slipnslide);
    State(39, "ComingOutDoor", scr_player_comingoutdoor);
    State(40, "SJump", scr_player_Sjump);
    State(41, "Victory", scr_player_victory);
    State(42, "SJumpPrep", scr_player_Sjumpprep);
    State(43, "Crouch", scr_player_crouch);
    State(44, "CrouchJump", scr_player_crouchjump);
    State(45, "CrouchSlide", scr_player_crouchslide);
    State(46, "Mach1", scr_player_mach1);
    State(47, "Mach2", scr_player_mach2);
    State(48, "MachSlide", scr_player_machslide);
    State(49, "Bump", scr_player_bump);
    State(50, "Hurt", scr_player_hurt);
    State(51, "FreeFall", scr_player_freefall);
    State(52, "Hang", scr_player_hang);
    State(53, "FreeFallLand", scr_player_freefallland);
    State(54, "Door", scr_player_door);
    State(55, "BarrelBounce", scr_player_barrelbounce);
    State(56, "BarrelCrouch", scr_player_barrelcrouch);
    State(57, "BarrelFloat", scr_player_barrelfloat);
    State(58, "BarrelMach2", scr_player_barrelmach2);
    State(59, "BarrelMach1", scr_player_barrelmach1);
    State(60, "BarrelFall", scr_player_barrelfall);
    State(61, "BarrelNormal", scr_player_barrelnormal);
    State(62, "BarrelSlipNSlide", scr_player_barrelslipnslide);
    State(63, "BarrelRoll", scr_player_barrelroll);
    State(64, "Current", scr_player_current);
    State(65, "Boulder", scr_player_boulder);
    State(66, "Mach3", scr_player_mach3);
    State(67, "FreeFallPrep", scr_player_freefallprep);
    State(68, "SJumpLand", scr_player_Sjumpland);
    State(69, "SlapDash", scr_player_slapdash);
    State(70, "Parry", scr_player_parry);
    State(71, "Breakdance", scr_player_breakdance);
    State(72, "Flustered", scr_player_flustered);
    State(73, "Shoulderbash", scr_player_shoulderbash);
    State(74, "GunShoot", scr_player_gunshoot);
    State(75, "Shoryuken", scr_player_shoryuken);
    State(76, "Pipe", scr_player_pipe);
    State(77, "Faceplant", scr_player_faceplant);
    State(78, "Ghost", scr_player_ghost);
    State(79, "Golf", scr_player_golf);
    State(80, "Thok", scr_player_thok);
    State(81, "Pogo", scr_player_pogo);
    State(82, "Wait", scr_player_wait);
    State(83, "Handstand", scr_player_handstand);
    State(84, "SideJumpPrep", scr_player_sidejumpprep);
    State(85, "SideJump", scr_player_sidejump);
    State(86, "Grow", scr_player_grow);
    State(87, "Hitstun", scr_player_hitstun, 1);
    State(88, "SlipBanan", scr_player_slipbanan);
    State(89, "Taxi", scr_player_taxi);
    State(90, "BallLOL", scr_player_balllol);
    State(91, "KungFu", scr_player_kungfu);
    State(92, "TackleOLD", scr_player_tackleold);
    State(93, "GameOver", scr_player_gameover);
    State(94, "TimesUp!", scr_player_timesup);
    State(95, "Ramp", scr_player_ramp);
    State(96, "WeenieMount", scr_player_weeniemount);
    State(97, "FireMove", scr_player_firemove);
    State(98, "PitFall", scr_player_pitfall);
    State(99, "HeroPep", scr_player_heropep);
    State(100, "HomingAttack", scr_playerS_homingattack);
    State(101, "Pinch", scr_player_pinch);
    State(102, "Start", scr_player_start);
    State(103, "SwingDingFinish", scr_player_swingdingfinish);
    State(104, "Seat", scr_player_seat);
    State(105, "Barrel", scr_player_barrel);
    State(106, "SmallPep", scr_player_smallpep);
    State(107, "SmallPepDash", scr_player_smallpepdash);
    State(108, "#RETRODeath", scr_player_RETROdeath);
    State(109, "Firework", scr_player_firework);
    State(110, "Nothing...", undefined);
    State(111, "LevelSelect", scr_player_levelselect);
    State(112, "Cheeseslime", scr_playerC_normal);
    State(113, "CheeseslimeAttack", scr_playerC_attack);
    State(114, "Actor", scr_player_actor);
    State(115, "KnightPepBump", scr_player_knightpepbump);
    State(116, "SecretPortal", undefined);
    State(117, "Held", scr_player_held);
    State(118, "Lunge", scr_player_lunge);
    State(119, "KungFuGrab", scr_player_kungfugrab);
    State(120, "NWallJump", scr_playerN_walljump);
    State(121, "KingBubble", scr_player_kingbubble);
    State(122, "NPCLocked", scr_player_npclocked);
    State(123, "ForcedFall", scr_player_forcedfall);
    State(124, "BombKnockback", scr_player_bombknockback);
    State(125, "HubEject", scr_player_hubeject);
    State(126, "SageLevelEntrance", scr_player_sagelevelentrance);
    State(127, "GateCutscene", scr_player_gatecutscene);
    State(128, "NoClip", scr_player_noclip);
}
