self.addSong("event:/music/soundtest/title", "Bo-gin Your Journey - UNI M.")
self.addSong("event:/music/soundtest/pause", "It's Bo Break-Time - UNI M.")
self.addSong("event:/music/soundtest/hub", "And This is My \nGlorious Mansion! - UNI M.")
self.addSong("event:/music/soundtest/midway", "Bad to the Bo - VI")
self.addSong("event:/music/soundtest/midwaysecret", "I Found a Mid Secret - UNI M.")
self.addSong("event:/music/soundtest/eerie", "Blud Lake - VI")
self.addSong("event:/music/soundtest/eeriecave", "A Broken Heart \nand a Bladder - UNI M.")
self.addSong("event:/music/soundtest/eeriecave_underwater", "A Broken Heart \nand a Bladder (Fish Mix) - UNI M.")
self.addSong("event:/music/soundtest/eeriesecret", "A Secret Resides at the \nBottom of the Lake - UNI M.")
self.addSong("event:/music/soundtest/eeriefish", "Unown's Death Scene - Mr.Unown, Froskii")
self.addSong("event:/music/soundtest/fishdance", "Strong House at Nighttime - UNI M.")
self.addSong("event:/music/soundtest/tuctime", "Its Bo Time! - VI")
self.addSong("event:/music/soundtest/lap", "Ring Around the Bosey - UNI M.")
self.addSong("event:/music/soundtest/pillar", "Tachyarrhythmia Rhythms - UNI M.")
self.addSong("event:/music/soundtest/credits", "The Bo Bash - UNI M.")
self.addSong("event:/music/soundtest/end", "The End of the \nBo-Ginning - UNI M.")
