hsp = random_range(5, 10)
vsp = random_range(5, 10)
dir_h = choose(1, -1)
dir_v = choose(1, -1)
alarm[0] = 30
image_index = irandom(image_number - 1)
image_angle = random_range(0, 360)
image_speed = 0
depth = -1
