xs = 1;
ys = 1;
sizex = 1;
sizey = 1;
enlarge = 0;
image_index = 0;
image_speed = 0;
draw_alpha = 0;
fade_out = false;
selection = 0;
selection_confirmed = false;
choice[0] = "Save Ed";
choice[1] = "Save The Others";
train_timer = 900;
audio_play_sound(snd_mainmenu_select, 1, 0);
