event_inherited();
up_sprite = spr_moray_up_walk;
right_sprite = spr_moray_right_walk;
down_sprite = spr_moray_down_walk;
left_sprite = spr_moray_left_walk;
up_sprite_idle = spr_moray_up_talk;
right_sprite_idle = spr_moray_right_talk;
down_sprite_idle = spr_moray_down_talk;
left_sprite_idle = spr_moray_left_talk;
action_sprite = false;
scene = 0;
x_dest[0] = x;
y_dest[0] = y;
actor_speed = 3;
axis_override = "nothing";
end_direction = "left";
walk_collider = -4;
npc_voice_sfx = snd_talk_moray;
