image_xscale = 2;
image_yscale = 2;
step = 0;
drawBat = true;
batImageIndex = 0;
flightAmp = 7;
flightFreq = 0.25;
image_blend = global.flavor_sprites ? #C95546 : c_white;
batYOff = 0;
actor_shake_init(true);
