randomize();
x = choose(100, 400, 800);
y = choose(300, 200);
timer = irandom_range(200, 600);
fadeid = -4;
captured = false;
ate = 0;
state = (0 << 0);
currentlayout = 1;
layout1tile3 = layer_get_id("Layout1tile3");
layout1tile2 = layer_get_id("Layout1tile2");
layout1tile1 = layer_get_id("Layout1tile1");
layout1obj = layer_get_id("Layout1obj");
layout2tile2 = layer_get_id("Layout2tile2");
layout2tile1 = layer_get_id("Layout2tile1");
layout2obj = layer_get_id("Layout2obj");
layout3tile2 = layer_get_id("Layout3tile2");
layout3tile1 = layer_get_id("Layout3tile1");
layout3obj = layer_get_id("Layout3obj");
layout4obj = layer_get_id("Layout4obj");
layout4tile3 = layer_get_id("Layout4tile3");
layout4tile2 = layer_get_id("Layout4tile2");
layout4tile1 = layer_get_id("Layout4tile1");
instance_deactivate_layer(layout2obj);
instance_deactivate_layer(layout3obj);
instance_deactivate_layer(layout4obj);
layer_set_visible(layout2obj, false);
layer_set_visible(layout2tile2, false);
layer_set_visible(layout2tile1, false);
layer_set_visible(layout3tile2, false);
layer_set_visible(layout3tile1, false);
layer_set_visible(layout3obj, false);
layer_set_visible(layout4obj, false);
layer_set_visible(layout4tile3, false);
layer_set_visible(layout4tile2, false);
layer_set_visible(layout4tile1, false);
