collectvanish = false;
collectboxid = -4;
in_the_void = false;
depth = 2;
global.collected = 0;
global.collectsound = mu_rankd;
sprite_index = choose(spr_bigcollect1, spr_bigcollect2, spr_bigcollect3, spr_bigcollect4, spr_bigcollect5, spr_bigcollect6);
image_speed = 0.35;
gotowardsPlayer = false;
