event_inherited();
depth = -2;
image_speed = 0.5;
image_xscale = 2;
image_yscale = 2;
animUp = true;
direction = 86 - random(8);
gravity_direction = 270;
gravity = 0.8;
speed = 4 + random(3);
hspeed += 2;
jumpCount = 0;
