keys = [];
buttons = [];
selected = 0;
key_selected = 0;
draw = 0;
offsetx = 0;
drawsp = 0;
backbuffer = 3;
depth = -201;
image_speed = 0.35;
array_push(keys, ["UP", global.keyboardp2up]);
array_push(keys, ["DOWN", global.keyboardp2down]);
array_push(keys, ["LEFT", global.keyboardp2left]);
array_push(keys, ["RIGHT", global.keyboardp2right]);
array_push(keys, ["JUMP", global.keyboardp2key_jump]);
array_push(keys, ["TILT", global.keyboardp2key_tilt]);
array_push(keys, ["SPECIAL", global.keyboardp2key_special]);
array_push(keys, ["TAUNT", global.keyboardp2key_taunt]);
array_push(keys, ["EXIT", "PRESS JUMP"]);
array_push(buttons, ["UP", global.keyboardp2up]);
array_push(buttons, ["DOWN", global.keyboardp2down]);
array_push(buttons, ["LEFT", global.keyboardp2left]);
array_push(buttons, ["RIGHT", global.keyboardp2right]);
array_push(buttons, ["JUMP", global.keyboardp2key_jump]);
array_push(buttons, ["TILT", global.keyboardp2key_tilt]);
array_push(buttons, ["SPECIAL", global.keyboardp2key_special]);
array_push(buttons, ["TAUNT", global.keyboardp2key_taunt]);
array_push(buttons, ["EXIT", "PRESS JUMP"]);
