optionselected = 0;
ini_open("optionData.ini");
global.heatmeter = ini_read_real("Settings", "heatmeter", 0);
global.coneballparry = ini_read_real("Settings", "coneballparry", 0);
global.moveset = ini_read_real("Settings", "moveset", 0);
global.attackmove = ini_read_real("Settings", "attackmove", 0);
global.checkpoints = ini_read_real("Settings", "checkpoints", 1);
ini_close();
optionsaved_heatmeter = global.heatmeter;
optionsaved_coneballparry = global.coneballparry;
optionsaved_moveset = global.moveset;
optionsaved_attackmove = global.attackmove;
optionsaved_checkpoints = global.checkpoints;
subtitle = "GO BACK TO MOD OPTIONS";
CursorY = -999;
ScrollY = 0;
depth = -100;
selecting = -1;
obj_Options_Mod_old.CursorY = -999;
canmove = false;
alarm[0] = 1;
