draw_set_font(global.font);
draw_set_halign(fa_center);
draw_option(150, 30 + ScrollY, "BACK", optionselected == 0);
draw_option(480, 100 + ScrollY, "HEATMETER", optionselected == 1);
draw_option(280, 150 + ScrollY, "ON", optionsaved_heatmeter);
draw_option(680, 150 + ScrollY, "OFF", !optionsaved_heatmeter);
draw_option(480, 200 + ScrollY, "WEAKER CONEBALL", optionselected == 2);
draw_option(280, 250 + ScrollY, "ON", optionsaved_coneballparry);
draw_option(680, 250 + ScrollY, "OFF", !optionsaved_coneballparry);
draw_option(480, 300 + ScrollY, "MOVESET", optionselected == 3);
draw_option(180, 350 + ScrollY, "DEFAULT", optionsaved_moveset == 0);
draw_option(480, 350 + ScrollY, "NEW", optionsaved_moveset == 1);
draw_option(780, 350 + ScrollY, "OLD", optionsaved_moveset == 2);
draw_option(480, 400 + ScrollY, "ATTACK MOVE", optionselected == 4);
draw_option(280, 450 + ScrollY, "DEFAULT", optionsaved_attackmove == 0);
draw_option(680, 450 + ScrollY, "GRAB", optionsaved_attackmove == 1);
draw_option(280, 500 + ScrollY, "SHOULDER", optionsaved_attackmove == 2);
draw_option(680, 500 + ScrollY, "KUNG FU", optionsaved_attackmove == 3);
draw_option(480, 550 + ScrollY, "LAP CHECKPOINTS", optionselected == 5);
draw_option(280, 600 + ScrollY, "ON", optionsaved_checkpoints);
draw_option(680, 600 + ScrollY, "OFF", !optionsaved_checkpoints);
draw_set_font(global.smallfont);
draw_set_halign(fa_center);
var _string_width = string_width(subtitle) + 32;
if (subtitle != "")
	draw_sprite_ext(spr_optionSubtitle, 0, 480, 521, _string_width / 32, 1, 0, c_white, 1);
draw_text(480, 512, subtitle);
