draw_set_font(global.creditsfont);
draw_text_colour(280, 50, string_hash_to_newline("ATRÁS"), c_white, c_white, c_white, c_white, (key_select == -1) ? 1 : 0.5);
draw_text_colour(420, 50, string_hash_to_newline("UP"), c_white, c_white, c_white, c_white, (key_select == 0) ? 1 : 0.5);
draw_text(580, 50, string_hash_to_newline(scr_keyname(global.key_up)));
draw_text_colour(420, 100, string_hash_to_newline("DOWN"), c_white, c_white, c_white, c_white, (key_select == 1) ? 1 : 0.5);
draw_text(580, 100, string_hash_to_newline(scr_keyname(global.key_down)));
draw_text_colour(420, 150, string_hash_to_newline("RIGHT"), c_white, c_white, c_white, c_white, (key_select == 2) ? 1 : 0.5);
draw_text(580, 150, string_hash_to_newline(scr_keyname(global.key_right)));
draw_text_colour(420, 200, string_hash_to_newline("LEFT"), c_white, c_white, c_white, c_white, (key_select == 3) ? 1 : 0.5);
draw_text(580, 200, string_hash_to_newline(scr_keyname(global.key_left)));
draw_text_colour(420, 250, string_hash_to_newline("JUMP"), c_white, c_white, c_white, c_white, (key_select == 4) ? 1 : 0.5);
draw_text(580, 250, string_hash_to_newline(scr_keyname(global.key_jump)));
draw_text_colour(420, 300, string_hash_to_newline("GRAB"), c_white, c_white, c_white, c_white, (key_select == 5) ? 1 : 0.5);
draw_text(580, 300, string_hash_to_newline(scr_keyname(global.key_slap)));
draw_text_colour(420, 350, string_hash_to_newline("DASH"), c_white, c_white, c_white, c_white, (key_select == 6) ? 1 : 0.5);
draw_text(580, 350, string_hash_to_newline(scr_keyname(global.key_attack)));
draw_text_colour(420, 400, string_hash_to_newline("TAUNT"), c_white, c_white, c_white, c_white, (key_select == 7) ? 1 : 0.5);
draw_text(580, 400, string_hash_to_newline(scr_keyname(global.key_taunt)));
draw_text_colour(420, 450, string_hash_to_newline("SPECIAL"), c_white, c_white, c_white, c_white, (key_select == 8) ? 1 : 0.5);
draw_text(580, 450, string_hash_to_newline(scr_keyname(global.key_special)));
draw_text_colour(420, 500, string_hash_to_newline("PAUSE"), c_white, c_white, c_white, c_white, (key_select == 9) ? 1 : 0.5);
draw_text(580, 500, string_hash_to_newline(scr_keyname(global.key_start)));
