menu[0] = "LETS GO";
menu[1] = "CHICKEN OUT";
draw_set_halign(fa_left);
draw_set_valign(fa_top);
global.player1 = "PS";
global.player2 = 0;
global.stocks = 3;
global.ArcadeDiffictulty = 0;
leviRate = 1.5;
selected = 0;
selectLerp = 0;
spacing = 50;
selectedCol = 255;
notSelectedCol = 139;
titleCol = 16777215;
reset = 0;
lyaxis = 0;
yeah = 0;
upButt = global.keyboardp1up;
downButt = global.keyboardp1down;
confirmButt = global.keyboardp1key_jump;
ass_trigger = false;
movedowncont = false;
moveupcont = false;
bgalpha = 0;
bgalphato = 0;
