send_player_data(socket, CMD_ROOM, obj_player.id, room)
send_player_data(socket, CMD_X, obj_player.id, obj_player.x)
send_player_data(socket, CMD_Y, obj_player.id, obj_player.y)
send_player_data(socket, CMD_X_SCALE, obj_player.id, obj_player.image_xscale)
send_player_data(socket, CMD_SPRITE, obj_player.id, obj_player.sprite_index)
send_player_data(socket, CMD_NAME, obj_player.id, obj_player.playername)
send_player_data(socket, CMD_MESSAGE, obj_player.id, obj_player.msg)
send_player_data(socket, CMD_ID, obj_player.id, string(obj_player.id))