event_inherited();
up_sprite = spr_npc_train_down;
right_sprite = spr_npc_train_down;
down_sprite = spr_npc_train_down;
left_sprite = spr_npc_train_down;
up_sprite_idle = spr_npc_train_down;
right_sprite_idle = spr_npc_train_down;
down_sprite_idle = spr_npc_train_down;
left_sprite_idle = spr_npc_train_down;
action_sprite = false;
scene = 0;
x_dest[0] = x;
y_dest[0] = y;
actor_speed = 3;
axis_override = "nothing";
end_direction = "left";
walk_collider = -4;
