instance_create(x, y, obj_battle_enemy_attack_martlet_genocide_feather_ext_explosion);
alarm[0] = 3;
feather_radius = 15;
feather_speed = 14;
feather_alpha = 1;
can_move = false;
can_fade_out = false;
fcreate_count = 4;
fcreate_decrease = 360 / fcreate_count;
fcreate_angle_diff = 0;
