depth = 149
image_speed = 0
image_index = irandom_range(0, (image_number - 1))
image_alpha = 0
vanishing = false
currentCurrent = -4
alarm[0] = random_range(60, 250)
vsp = random_range(-1, -2)
hasLine = chance(25)
strength = irandom_range(0, 3)
xOffset = irandom_range((-strength), strength)
time = irandom_range(0, 5)
