if (live_call())
    return global.live_result;

audio_play_sound(snd_kamehamehablast, 1, 0);
scr_screenshake_battle(6, 2);
image_alpha = 1;
direction = 90;
image_angle = 90;
image_speed = 0;
depth = -100;
scene = 0;
cutscene_timer = 0;
laser_width = 0;
laser_length = 0;
laser_length_max = 130;
laser_active = true;
laser_speed = 20;
laser_blocked = false;
laser_grow = true;
laser_shrink = false;
laser_x1 = 0;
laser_x2 = 0;
laser_y1 = 0;
laser_y2 = 0;
sin_timer = 0;
impact_frame_current = 0;
impact_frame_max = 8;
impact_frame_speed = 0.5;
laser_frame_current = 0;
laser_frame_max = 1;
laser_frame_speed = 0.25;
