event_inherited();
depth = -5;
journalId = 5;
var bn = "battles.loox.";
normalSprite = sprite_index;
hurtSprite = spr_looxdamage;
dustFilename = "rh_l";
name = dxd_raw(bn + "name");
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
bt_add_act(bn, "act0");
bt_add_act(bn, "act1");
bt_add_act(bn, "act2");
maxHp = 50;
hp = maxHp;
defense = 4;
attack = 4;
xpReward = 7;
goldReward = 5;
mercyResistance = 15;
flavorColor = make_color_rgb(255 - irandom(15), 119 + (irandom(15) * choose(-1, 1)), 109 + (irandom(15) * choose(-1, 1)));

if (global.flavor_sprites)
    image_blend = flavorColor;

doReturnAnim = false;
vcheck = false;
vstare = 0;
vstaredid = false;
vpickon = 0;
vpickondid = false;
vmurder = false;
vchallenger = -1;
vdocombostare = false;
armOffset = 0;
armDir = 1;
isVegetoid = false;
attackType = -1;
bulletSide = 0;
attackTime = 0;
attackStage = 0;
overrideSmallRing = false;
needToCenter = false;
isOtherLoox = false;
otherLoox = 0;
alarm[0] = 240;
