draw_set_font(global.font);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_set_color(c_white);
draw_sprite_tiled_ext(bg_cowboytask, -1, bgx, bgy, 1, 1, c_white, 1);
draw_set_font(global.thinfont);
draw_set_valign(fa_bottom);
draw_set_halign(fa_left);
draw_text_fancy(20, get_game_height() - 20, string_get("menu/cowboytask/exit"));
var _padx = 80;
var _pady = 130;
save_open();
var _achspr1 = asset_get_index(string("spr_cowboytask_{0}1", global.levelname));
var _achspr2 = asset_get_index(string("spr_cowboytask_{0}2", global.levelname));
var _achspr3 = asset_get_index(string("spr_cowboytask_{0}3", global.levelname));
draw_sprite_ext(_achspr1, ini_read_real("Achievements", string("{0}1", global.levelname), false), _padx - 50, _pady - 50, 1, 1, 0, c_white, (select == 0) ? 1 : 0.5);
draw_sprite_ext(_achspr2, ini_read_real("Achievements", string("{0}2", global.levelname), false), get_game_width() - _padx - 50, (get_game_height() / 2) - 50, 1, 1, 0, c_white, (select == 1) ? 1 : 0.5);
draw_sprite_ext(_achspr3, ini_read_real("Achievements", string("{0}3", global.levelname), false), _padx - 50, get_game_height() - _pady - 50, 1, 1, 0, c_white, (select == 2) ? 1 : 0.5);
save_close();
draw_set_font(global.thinfont);
draw_set_valign(fa_middle);
draw_set_halign(fa_left);
__draw_text_colour_hook(_padx + 70, _pady, string_concat(string_get("tasks/" + string("{0}1", global.levelname)), "\n", string_get("tasks/" + string("{0}1", global.levelname) + "desc")), c_white, c_white, c_white, c_white, (select == 0) ? 1 : 0.5);
draw_set_halign(fa_right);
__draw_text_colour_hook(get_game_width() - _padx - 70, get_game_height() / 2, string_concat(string_get("tasks/" + string("{0}2", global.levelname)), "\n", string_get("tasks/" + string("{0}2", global.levelname) + "desc")), c_white, c_white, c_white, c_white, (select == 1) ? 1 : 0.5);
draw_set_halign(fa_left);
__draw_text_colour_hook(_padx + 70, get_game_height() - _pady, string_concat(string_get("tasks/" + string("{0}3", global.levelname)), "\n", string_get("tasks/" + string("{0}3", global.levelname) + "desc")), c_white, c_white, c_white, c_white, (select == 2) ? 1 : 0.5);
