part_snowfallsys = part_system_create();
part_snowfallEm = part_emitter_create(part_snowfallsys);
part_system_depth(part_snowfallsys, -9999);
part_snowfall = part_type_create();
part_type_sprite(part_snowfall, 636, 0, 0, 1);
part_type_size(part_snowfall, 1, 1, 0, 0);
part_type_colour2(part_snowfall, c_white, c_white);
part_type_alpha3(part_snowfall, 0.25, 0.95, 0);
part_type_speed(part_snowfall, 0.3, 1.2, 0, 0);
part_type_direction(part_snowfall, 250, 290, 0, 0);
part_type_orientation(part_snowfall, 0, 359, random_range(-2, 2), 0.1, 1);
part_type_life(part_snowfall, 250, 2000);
part_type_blend(part_snowfall, 1);
part_startsys = part_system_create();
part_startEm = part_emitter_create(part_startsys);
part_system_depth(part_startsys, -9999);
part_emitter_region(part_startsys, part_startEm, 0, room_width, -200, room_height, 0, 0);
part_emitter_burst(part_startsys, part_startEm, part_snowfall, room_width / 8);
part_emitter_region(part_snowfallsys, part_snowfallEm, 0, room_width, 0, __view_get(e__VW.YView, 0), 3, 0);
part_emitter_stream(part_snowfallsys, part_snowfallEm, part_snowfall, -8);
