instance_destroy(obj_battle_enemy_attack_goosic_speaker);
instance_destroy(obj_battle_enemy_attack_goosic_speaker_note);
instance_destroy(obj_battle_enemy_attack_jandroid_slippery_floor_warning);
instance_destroy(obj_battle_enemy_attack_jandroid_slippery_floor_bucket);
instance_destroy(obj_battle_enemy_attack_jandroid_slippery_floor_generator, false);

with (obj_dialogue_box_battle_transformation_any)
    event_user(0);

audio_listener_position(0, 0, 0);
