selected_level = 0
selected_world = 0
active = false
alarm[0] = 30
global.leveltorestart = -4
world_array[0] = "BO NOISE ACTUAL LEVELS"
world_array[1] = "EXTRA GARBAGE BELOW! WITH SOME SORT OF EFFORT PUT INTO IT!"
world_array[2] = "SHITPOST STUFF"
world_array[3] = "SHITPOST STUFF 2"
world_array[4] = "BO UNLOCK"
world_array[5] = "PEPPERMAN"
level_array[0][0] = ["HUB", hub_entrancehall, "hub"]
level_array[0][1] = ["MIDWAY", midway_1, "midway"]
level_array[0][2] = ["LAKE EERIE", water_1, "fish"]
level_array[0][3] = ["TESTROOM", rm_testies, "test"]
level_array[1][0] = ["VIRDESERT", virdesert_1, "midland"]
level_array[1][1] = ["MARIO BROS 2", smb_1_32, "wahoo"]
level_array[1][2] = ["MANSION 2 BUT WHAT IF IT WAS SCRAPPED", mansiondelta_1, "dungeorune"]
level_array[2][0] = ["TOP IN WORLD 3", glop_1, "hell"]
toppin_info[0] = [0, spr_toppinshroom]
toppin_info[1] = [0, spr_toppincheese]
toppin_info[2] = [0, spr_toppintomato]
toppin_info[3] = [0, spr_toppinsausage]
toppin_info[4] = [0, spr_toppinpineapple]
stickpressed = false
