// Generated by Ultimate_GMS2_Decompiler_v3.csx

// GameSpecificData Enums
enum e__VW 
{
	XView = 0,
	YView = 1,
	WView = 2,
	HView = 3,
	Angle = 4,
	HBorder = 5,
	VBorder = 6,
	HSpeed = 7,
	VSpeed = 8,
	Object = 9,
	Visible = 10,
	XPort = 11,
	YPort = 12,
	WPort = 13,
	HPort = 14,
	Camera = 15,
	SurfaceID = 16,
}

enum e__BG 
{
	Visible = 0,
	Foreground = 1,
	Index = 2,
	X = 3,
	Y = 4,
	Width = 5,
	Height = 6,
	HTiled = 7,
	VTiled = 8,
	XScale = 9,
	YScale = 10,
	HSpeed = 11,
	VSpeed = 12,
	Blend = 13,
	Alpha = 14,
}

// Generic Enum Declaration
enum UnknownEnum 
{
}