image_speed = 0.35;
sprite_index = spr_gerome_idle;
grabbed = 0;
hsp = 0;
vsp = 0;
grav = 0.5;
flash = 1;
unpickable = 0;
hp = 0;
grounded = 1;
state = states.normal;
playerid = 324; // unused i guess, and the player is not obj_pepgoblin, so yeah
mask_index = spr_player_mask;
depth = -5;
platformid = noone;
hsp_carry = 0;
vsp_carry = 0;
thrown = 0;
