var color_part;

color_part = make_colour_rgb(228, 69, 101);
part_embersys = part_system_create();
part_emberEm = part_emitter_create(part_embersys);
part_system_depth(part_embersys, 60);
part_ember_small = part_type_create();
part_type_sprite(part_ember_small, 2120, 0, 0, false);
part_type_size(part_ember_small, 2, 2, 0, 0);
part_type_colour1(part_ember_small, color_part);
part_type_alpha2(part_ember_small, 1, 0);
part_type_speed(part_ember_small, 0.8, 1.1, 0, 0);
part_type_direction(part_ember_small, 75, 105, 0, 0);
part_type_life(part_ember_small, 300, 300);
part_type_blend(part_ember_small, false);
part_ember_medium = part_type_create();
part_type_sprite(part_ember_medium, 2119, 0, 0, false);
part_type_size(part_ember_medium, 2, 2, 0, 0);
part_type_colour1(part_ember_medium, color_part);
part_type_alpha2(part_ember_medium, 1, 0);
part_type_speed(part_ember_medium, 0.6, 0.9, 0, 0);
part_type_direction(part_ember_medium, 75, 105, 0, 0);
part_type_life(part_ember_medium, 325, 325);
part_type_blend(part_ember_medium, false);
part_ember_large = part_type_create();
part_type_sprite(part_ember_large, 2117, 0, 0, false);
part_type_size(part_ember_large, 2, 2, 0, 0);
part_type_colour1(part_ember_large, color_part);
part_type_alpha2(part_ember_large, 1, 0);
part_type_speed(part_ember_large, 0.4, 0.7, 0, 0);
part_type_direction(part_ember_large, 75, 105, 0, 0);
part_type_life(part_ember_large, 350, 350);
part_type_blend(part_ember_large, false);
part_emitter_region(part_embersys, part_emberEm, 0, room_width, 0, 250, 0, 0);
part_emitter_burst(part_embersys, part_emberEm, part_ember_small, 3);
part_emitter_burst(part_embersys, part_emberEm, part_ember_medium, 2);
part_emitter_burst(part_embersys, part_emberEm, part_ember_large, 1);
part_emitter_region(part_embersys, part_emberEm, 0, room_width, 250, 250, 3, 0);
diamond_width = 60;
diamond_width_current = 0;
diamond_height = 140;
diamond_x[0] = 640 - diamond_width - 20;
diamond_x[1] = 0 + diamond_width + 20;
diamond_y = 120;
diamond_y_original = 115;
diamond_y_shift = 30;
diamond_sin_deg = 0;
diamond_alpha = 1;
