sprite_index = spr_battle_flowey_final_background;
shader = 15;
u_time = shader_get_uniform(shader, "time");
u_uvs = shader_get_uniform(shader, "uvs");
uvs = sprite_get_uvs(sprite_index, 0);
sh_uvs = [uvs[0], uvs[1], uvs[2], uvs[3]];
texture = sprite_get_texture(spr_background_enemy_battle_guardener_wind, 0);
u_texture = shader_get_sampler_index(shader, "distort_texture");
pixelate_surf = -1;
