bgX = 0;
bgY = 0;
afterimg = ds_list_create();
mouseVisible = false;
guiSurface = noone;
alarm[0] = 5;
afterimg_buffer = 0;
mouse_buffer = 0;
generalAlpha = 1;
randomize();
palette = choose(0, 1, 2, 3, 4);
previousX = device_mouse_x_to_gui(0);
previousY = device_mouse_y_to_gui(0);
oldWidth = window_get_width();
oldHeight = window_get_height();
scaleMode = 0;
actualWidth = window_get_width();
actualHeight = window_get_height();
app_scale = 1;
window_set_cursor(cr_none);
starting_fill = 0;
flash_color = 255;
mouse_scale = 1;
mouse_alpha = 0;
cursor_x = device_mouse_x_to_gui(0);
cursor_y = device_mouse_y_to_gui(0);
