var catSoda = addCategory("credits_lead")
var catDirectors = addCategory("credits_directors")
var catProgrammers = addCategory("credits_programmers")
var catArtist = addCategory("credits_artists")
var catLevels = addCategory("credits_levels")
var catMusicians = addCategory("credits_music")
var catSFX = addCategory("credits_sfx")
var catQA = addCategory("credits_qa")
var catLocalizationHead = addCategory("credits_langhead")
var catLocalizationES = addCategory("credits_langES")
var catLocalizationRU = addCategory("credits_langRU")
var catLocalizationPTBR = addCategory("credits_langPTBR")
var catVoicework = addCategory("credits_voice")
var catBredi = addCategory("credits_trailer")
var catWebsite = addCategory("credits_website")
var catPlaytest = addCategory("credits_playtest")
var catSpecial = addCategory("credits_thanks")
var catPizza = addCategory("credits_tdp")
var catYou = addCategory("credits_and")
addCredit(catSoda, "Sodamang", [spr_candysona_idle6, spr_candysona_dead6])
addCredit(catDirectors, "Fishibi", [spr_candysona_idle1, spr_candysona_dead1])
addCredit(catDirectors, "Alejandro \"LOSTMAN\" Vargas", [spr_candysona_idle21, spr_candysona_dead21])
addCredit(catDirectors, "MACKACHE", [spr_candysona_idle9, spr_candysona_dead9])
addCredit(catDirectors, "Mr. Unown", [spr_candysona_idle7, spr_candysona_dead7])
addCredit(catDirectors, "PierRoulette", [spr_candysona_idle25, spr_candysona_dead25])
addCredit(catProgrammers, "AwfulNasty", [spr_candysona_idle34, spr_candysona_dead34])
addCredit(catProgrammers, "Core", [spr_candysona_idle12, spr_candysona_dead12]).addPaintTopper([0, 58, 59])
addCredit(catProgrammers, "Alejandro \"LOSTMAN\" Vargas", [spr_candysona_idle21, spr_candysona_dead21])
addCredit(catProgrammers, "Mr. Unown", [spr_candysona_idle7, spr_candysona_dead7])
addCredit(catProgrammers, "Saiasha", [spr_candysona_idle36, spr_candysona_dead36])
addCredit(catProgrammers, "SCOUT-THE-SNOW", [spr_candysona_idle26, spr_candysona_dead26]).addPaintTopper([52, 53, 54, 55])
addCredit(catArtist, "902", [spr_candysona_idle19, spr_candysona_dead19])
addCredit(catArtist, "Baphalopod", [spr_candysona_idle8, spr_candysona_dead8]).addPaintTopper([32])
addCredit(catArtist, "Bredi", [spr_candysona_idle11, spr_candysona_dead11])
addCredit(catArtist, "Capn_Mongo", [spr_candysona_idle31, spr_candysona_dead31]).addPaintTopper([18, 19, 20])
addCredit(catArtist, "DaJumpJump", [spr_candysona_idle33, spr_candysona_dead33])
addCredit(catArtist, "Dylfinedas", [spr_candysona_idle37, spr_candysona_dead37])
addCredit(catArtist, "Fishibi", [spr_candysona_idle1, spr_candysona_dead1])
addCredit(catArtist, "Glub", [spr_candysona_idle27, spr_candysona_dead27]).addPaintTopper([25, 26, 27])
addCredit(catArtist, "Lukee", [spr_candysona_idle24, spr_candysona_dead24]).addPaintTopper([47, 48, 49])
addCredit(catArtist, "Only1indigo", [spr_candysona_idle5, spr_candysona_dead5]).addPaintTopper([46])
addCredit(catArtist, "OSP", [spr_candysona_idle18, spr_candysona_dead18]).addPaintTopper([1, 2, 3, 4, 5, 6])
addCredit(catArtist, "RetroDiskette", [spr_candysona_idle40, spr_candysona_dead40]).addPaintTopper([41, 42, 43, 56])
addCredit(catArtist, "Sappy", [spr_candysona_idle3, spr_candysona_dead3]).addPaintTopper([36, 37, 38])
addCredit(catArtist, "Ufra", [spr_candysona_idle32, spr_candysona_dead32]).addPaintTopper([28, 29, 30, 31])
addCredit(catArtist, "Catherine \"welegi\" Welegi", [spr_candysona_idle39, spr_candysona_dead39]).addPaintTopper([7, 8, 24])
addCredit(catArtist, "ZPERKZ", [spr_candysona_idle4, spr_candysona_dead4]).addPaintTopper([39, 40, 44, 45])
addCredit(catLevels, "Capn_Mongo", [spr_candysona_idle31, spr_candysona_dead31]).addPaintTopper([18, 19, 20])
addCredit(catLevels, "HyperTem", [spr_candysona_idle17, spr_candysona_dead17])
addCredit(catLevels, "McDoodle", [spr_candysona_idle30, spr_candysona_dead30]).addPaintTopper([50, 51])
addCredit(catLevels, "Only1indigo", [spr_candysona_idle5, spr_candysona_dead5]).addPaintTopper([46])
addCredit(catMusicians, "CableChords", [spr_candysona_idle20, spr_candysona_dead20])
addCredit(catMusicians, "PaperKitty", [spr_candysona_idle23, spr_candysona_dead23])
addCredit(catMusicians, "Pteracotta", [spr_candysona_idle22, spr_candysona_dead22])
addCredit(catMusicians, "RedTV53", [spr_candysona_idle16, spr_candysona_dead16])
addCredit(catMusicians, "RodMod", [spr_candysona_idle15, spr_candysona_dead15])
addCredit(catMusicians, "Stewart Keller", [spr_candysona_idle41, spr_candysona_dead41])
addCredit(catMusicians, "The8BitDrummer", [spr_candysona_idle42, spr_candysona_dead42])
addCredit(catSFX, "gaproo", [spr_candysona_idle35, spr_candysona_dead35])
addCredit(catSFX, "Glub", [spr_candysona_idle27, spr_candysona_dead27]).addPaintTopper([25, 26, 27])
addCredit(catSFX, "OSP", [spr_candysona_idle18, spr_candysona_dead18]).addPaintTopper([1, 2, 3, 4, 5, 6])
addCredit(catSFX, "SCOUT-THE-SNOW", [spr_candysona_idle26, spr_candysona_dead26]).addPaintTopper([52, 53, 54, 55])
addCredit(catQA, "Alejandro \"LOSTMAN\" Vargas", [spr_candysona_idle21, spr_candysona_dead21])
addCredit(catQA, "OSP", [spr_candysona_idle18, spr_candysona_dead18]).addPaintTopper([1, 2, 3, 4, 5, 6])
addCredit(catQA, "Puffballspeakerbox", [spr_candysona_idle28, spr_candysona_dead28]).addPaintTopper([11, 12, 13, 14])
addCredit(catLocalizationHead, "Sodamang", [spr_candysona_idle6, spr_candysona_dead6])
addCredit(catLocalizationHead, "Alejandro \"LOSTMAN\" Vargas", [spr_candysona_idle21, spr_candysona_dead21])
addCredit(catLocalizationHead, "PierRoulette", [spr_candysona_idle25, spr_candysona_dead25])
addCredit(catLocalizationHead, "Zhakich")
addCredit(catLocalizationES, "902", [spr_candysona_idle19, spr_candysona_dead19])
addCredit(catLocalizationES, "Embo")
addCredit(catLocalizationES, "Glub", [spr_candysona_idle27, spr_candysona_dead27]).addPaintTopper([25, 26, 27])
addCredit(catLocalizationES, "JoeGriddleCake")
addCredit(catLocalizationES, "Alejandro \"LOSTMAN\" Vargas", [spr_candysona_idle21, spr_candysona_dead21])
addCredit(catLocalizationES, "SaltyPow")
addCredit(catLocalizationRU, "Bepiou")
addCredit(catLocalizationRU, "Polmups")
addCredit(catLocalizationRU, "Zhakich")
addCredit(catLocalizationPTBR, "Bredi", [spr_candysona_idle11, spr_candysona_dead11])
addCredit(catLocalizationPTBR, "Capn_Mongo", [spr_candysona_idle31, spr_candysona_dead31]).addPaintTopper([18, 19, 20])
addCredit(catVoicework, "RedTV53", [spr_candysona_idle16, spr_candysona_dead16])
addCredit(catVoicework, "HyperTem", [spr_candysona_idle17, spr_candysona_dead17])
addCredit(catVoicework, "McDoodle", [spr_candysona_idle30, spr_candysona_dead30]).addPaintTopper([50, 51])
addCredit(catVoicework, "Sage A. \"CarlmanZ\" Rollins", [spr_candysona_idle43, spr_candysona_dead43])
addCredit(catVoicework, "Catherine \"welegi\" Welegi", [spr_candysona_idle39, spr_candysona_dead39]).addPaintTopper([7, 8, 24])
addCredit(catBredi, "Bredi", [spr_candysona_idle11, spr_candysona_dead11])
addCredit(catWebsite, "CableChords", [spr_candysona_idle20, spr_candysona_dead20])
addCredit(catWebsite, "Bredi", [spr_candysona_idle11, spr_candysona_dead11])
addCredit(catWebsite, "Capn_Mongo", [spr_candysona_idle31, spr_candysona_dead31]).addPaintTopper([18, 19, 20])
addCredit(catWebsite, "Glub", [spr_candysona_idle27, spr_candysona_dead27]).addPaintTopper([25, 26, 27])
addCredit(catWebsite, "PierRoulette", [spr_candysona_idle25, spr_candysona_dead25])
addCredit(catWebsite, "Catherine \"welegi\" Welegi", [spr_candysona_idle39, spr_candysona_dead39]).addPaintTopper([7, 8, 24])
addCredit(catPlaytest, "Blizmite").addPaintTopper([33])
addCredit(catPlaytest, "CARIO55555")
addCredit(catPlaytest, "Dr. Engineer")
addCredit(catPlaytest, "DREADMAN")
addCredit(catPlaytest, "FulsomeFrog8789").addPaintTopper([34])
addCredit(catPlaytest, "Guycappy")
addCredit(catPlaytest, "?JDrive").addPaintTopper([9, 10, 57])
addCredit(catPlaytest, "Kairinkarin").addPaintTopper([35])
addCredit(catPlaytest, "Kirm")
addCredit(catPlaytest, "Scrufftuna").addPaintTopper([21, 22, 23])
addCredit(catPlaytest, "Puffballspeakerbox", [spr_candysona_idle28, spr_candysona_dead28]).addPaintTopper([11, 12, 13, 14])
addCredit(catPlaytest, "Otto")
addCredit(catPlaytest, "Randy.")
addCredit(catPlaytest, "Thinkman")
addCredit(catPlaytest, "Zhakich")
addCredit(catSpecial, "Albinostream")
addCredit(catSpecial, "AmyAcket")
addCredit(catSpecial, "BrownSugar")
addCredit(catSpecial, "CRUST")
addCredit(catSpecial, "DanDoesThings")
addCredit(catSpecial, "Emmet")
addCredit(catSpecial, "EpicMegaCookie").addPaintTopper([17])
addCredit(catSpecial, "Extended-Tangent")
addCredit(catSpecial, "FrozenCowJuice")
addCredit(catSpecial, "Foushe", [spr_candysona_idle14, spr_candysona_dead14])
addCredit(catSpecial, "H.")
addCredit(catSpecial, "Heinzlike", [spr_candysona_idle13, spr_candysona_dead13])
addCredit(catSpecial, "JoeGriddleCake")
addCredit(catSpecial, "JuniPinPan")
addCredit(catSpecial, "kanyeah", [spr_candysona_idle29, spr_candysona_dead29])
addCredit(catSpecial, "kaytea42")
addCredit(catSpecial, "Kyoobot")
addCredit(catSpecial, "Lillylowexpectations", [spr_candysona_idle10, spr_candysona_dead10])
addCredit(catSpecial, "Kette", [spr_candysona_idle2, spr_candysona_dead2])
addCredit(catSpecial, "lerp32")
addCredit(catSpecial, "MiaCDi").addPaintTopper([15, 16])
addCredit(catSpecial, "Ollenpac")
addCredit(catSpecial, "Oni")
addCredit(catSpecial, "Porky")
addCredit(catSpecial, "Randy.")
addCredit(catSpecial, "SaltyPow")
addCredit(catSpecial, "ScrapHat")
addCredit(catSpecial, "ScurvyBiscuit")
addCredit(catSpecial, "Somniac")
addCredit(catSpecial, "Swanky")
addCredit(catSpecial, "u4mhh")
addCredit(catSpecial, "Wormdotcom")
addCredit(catSpecial, "Yabcab", [spr_candysona_idle38, spr_candysona_dead38])
addCredit(catPizza, "McPig")
addCredit(catPizza, "Sertif")
addCredit(catPizza, "ClascyJitto")
addCredit(catPizza, "Mr. Sauceman")
addCredit(catPizza, "Post Elvis")
addCredit(catYou, lang_get("credits_you"), [spr_player_PZ_idleAnim_credits, spr_player_PZ_stun]).playerPalette = true
var cindex = 0
var unsetSprites = [[spr_grandpop, spr_grandpop_freed], [spr_icegrandson, spr_icegrandson_panic], [spr_grandpacone, spr_grandpacone_speak]]
var set_last = array_length(unsetSprites) - 1

for (var c = 0; c < categoryCount; c++)
{
	var cat = creditEntries[c][1]
	
	for (var i = 0; i < array_length(cat); i++)
	{
		var ent = cat[i]
		ent.index = cindex
		
		if (ent.spr_idle == spr_null)
		{
			var chosenSet = irandom_range(0, set_last)
			ent.spr_idle = unsetSprites[chosenSet][0]
			ent.spr_dead = unsetSprites[chosenSet][1]
			ent.create()
		}
		else
		{
			with (ent.object_id)
				index = cindex
		}
		
		cindex++
	}
}
