instance_destroy(obj_battle_enemy_attack_ceroba_flower_spiral_bullet);
instance_destroy(obj_battle_enemy_attack_ceroba_flower_spiral_spawner);

with (obj_dialogue_box_battle_transformation_any)
    event_user(0);
