var DONTREAD = "DANG, I HOPE MY HINT WASN'T TOO OBVIOUS.";
DONTREAD = "IN CASE YOU'RE CONFUSED, WELCOME.";
DONTREAD = "WE'RE GLAD YOU'VE MADE IT.";
DONTREAD = "WELL, I HAVE SOME MORE ADVICE FOR YOU.";
DONTREAD = "DON'T NOT NOT NOT TELEPORT.";
DONTREAD = "JUST, IT BREAKS THE LAWS OF SPACE AND TIME COMPLETELY.";
DONTREAD = "PERSONALLY, I DON'T BELIEVE IN THAT.";
