draw_set_font(global.font);
draw_set_halign(fa_center);
draw_option(150, 30 + ScrollY, "BACK", optionselected == 0);
draw_option(480, 100 + ScrollY, "SCORE FONT", optionselected == 1);
draw_option(180, 150 + ScrollY, "CANDLE", optionsaved_newscorefont == 2);
draw_option(480, 150 + ScrollY, "RANK CANDLE", optionsaved_newscorefont == 1);
draw_option(780, 150 + ScrollY, "DEMO", optionsaved_newscorefont == 0);
draw_option(480, 200 + ScrollY, "PLAYER ANIMATIONS", optionselected == 2);
draw_option(280, 250 + ScrollY, "DEFAULT", optionsaved_newplayeranim == 0);
draw_option(680, 250 + ScrollY, "NEW", optionsaved_newplayeranim == 1);
draw_option(280, 300 + ScrollY, "ALT", optionsaved_newplayeranim == 2);
draw_option(680, 300 + ScrollY, "CLASSIC", optionsaved_newplayeranim == 3);
draw_option(480, 350 + ScrollY, "VISUAL E RANK STACK", optionselected == 3);
draw_option(280, 400 + ScrollY, "ON", optionsaved_erankstack);
draw_option(680, 400 + ScrollY, "OFF", !optionsaved_erankstack);
draw_option(480, 450 + ScrollY, "SLOPE ANGLE", optionselected == 4);
draw_option(280, 500 + ScrollY, "ON", optionsaved_slopeangle);
draw_option(680, 500 + ScrollY, "OFF", !optionsaved_slopeangle);
draw_option(480, 550 + ScrollY, "MACH SFX", optionselected == 5);
draw_option(280, 600 + ScrollY, "DEFAULT", !optionsaved_machsfx);
draw_option(680, 600 + ScrollY, "CLASSIC", optionsaved_machsfx);
draw_option(480, 650 + ScrollY, "EGGPLANT COMBO TITLES", optionselected == 6);
draw_option(280, 700 + ScrollY, "ON", optionsaved_eggplantcombo);
draw_option(680, 700 + ScrollY, "OFF", !optionsaved_eggplantcombo);
draw_option(480, 750 + ScrollY, "OLD HUD", optionselected == 7);
draw_option(280, 800 + ScrollY, "ON", optionsaved_oldhud);
draw_option(680, 800 + ScrollY, "OFF", !optionsaved_oldhud);
draw_option(480, 850 + ScrollY, "HARRY FREEZE", optionselected == 8);
draw_option(280, 900 + ScrollY, "ON", optionsaved_harryfreeze);
draw_option(680, 900 + ScrollY, "OFF", !optionsaved_harryfreeze);
draw_option(480, 950 + ScrollY, "NEW PIZZELLE VOICELINES", optionselected == 9);
draw_option(280, 1000 + ScrollY, "ON", optionsaved_newvoicelines);
draw_option(680, 1000 + ScrollY, "OFF", !optionsaved_newvoicelines);
draw_option(480, 1050 + ScrollY, "DESTROYABLES", optionselected == 10);
draw_option(280, 1100 + ScrollY, "DEFAULT", optionsaved_destroyables == 0);
draw_option(680, 1100 + ScrollY, "FINALIZED", optionsaved_destroyables == 1);
draw_option(280, 1150 + ScrollY, "SEPTEMBER", optionsaved_destroyables == 2);
draw_option(680, 1150 + ScrollY, "CLASSIC", optionsaved_destroyables == 3);
draw_option(480, 1200 + ScrollY, "DISCORD RICH PRESENCE", optionselected == 11);
draw_option(280, 1250 + ScrollY, "ON", optionsaved_richpresence);
draw_option(680, 1250 + ScrollY, "OFF", !optionsaved_richpresence);
draw_set_font(global.smallfont);
var _string_width = string_width(subtitle) + 32;
if (subtitle != "")
	draw_sprite_ext(spr_optionSubtitle, 0, 480, 521, _string_width / 32, 1, 0, c_white, 1);
draw_text(480, 512, subtitle);
