instance_destroy(obj_flowey_battle_phase_2_weakpoint);
instance_destroy(obj_flowey_battle_phase_2_weakpoint_spikes);
instance_destroy(obj_flowey_battle_phase_2_weakpoint_vines);
instance_destroy(obj_flowey_battle_phase_2_clay_droop_bullet);
instance_destroy(obj_flowey_battle_phase_2_clay_eyedrop);
instance_destroy(obj_flowey_battle_phase_2_clay_floor);
