optionselected = 0;
scr_initinput();
subtitle = "GO BACK TO MAIN SCREEN";
CursorY = -999;
ScrollY = 0;
depth = -100;
selecting = false;
obj_Options_Main.CursorY = -999;
canmove = false;
alarm[0] = 1;
