draw_set_halign(fa_center);
draw_set_font(global.font);
draw_option(150, 30 + ScrollY, "BACK", optionselected == 0);
draw_option(800, 30 + ScrollY, "GAMEPAD", optionselected == 0);
var _yy = 50;
var _x1 = 400;
var _x2 = 600;
draw_option(_x1, _yy + ScrollY, "UP", optionselected == 1);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_up));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "RIGHT", optionselected == 2);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_right));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "LEFT", optionselected == 3);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_left));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "DOWN", optionselected == 4);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_down));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "JUMP", optionselected == 5);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_jump));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "ATTACK", optionselected == 6);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_attack));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "TAUNT", optionselected == 7);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_taunt));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "SHOOT", optionselected == 8);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_shoot));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "DASH", optionselected == 9);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_sprint));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "START", optionselected == 10);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_start));
_yy += 50;
draw_option(_x1, _yy + ScrollY, "SPECIAL", optionselected == 11);
draw_text(_x2, _yy + ScrollY, scr_keyname(global.key_special));
_yy += 50;
draw_set_font(global.smallfont);
var _string_width = string_width(subtitle) + 32;
if (subtitle != "")
	draw_sprite_ext(spr_optionSubtitle, 0, 480, 521, _string_width / 32, 1, 0, c_white, 1);
draw_text(480, 512, subtitle);
