damage_number = scr_determine_damage_number_enemy("ed", "void", "void");
image_index = irandom_range(0, image_number - 1);
can_fall = false;
image_alpha = 0;
gravity = 1.5;
vspeed = -20;
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
