damage_number = scr_determine_damage_number_enemy("dalv", "void", "void");
audio_play_sound(snd_undertale_appear, 1, 0);
image_speed = 0.4;
image_index = 0;
image_alpha = 0;
image_angle = 270;
angle_intensity = 3;
move_speed = 12;
move_speed_max = 20;
move_speed_increase = 1;
move = false;
