layer_depth("Tiles_BG", 200);
layer_depth("Tiles_BG2", 199);
layer_depth("Tiles_BG3", 198);
layer_depth("Tiles_1", 100);
layer_depth("Tiles_2", 98);
layer_depth("Tiles_3", 97);
layer_depth("Tiles_4", 96);
layer_depth("Tiles_Foreground1", -30);
layer_depth("Tiles_Foreground2", -31);
layer_depth("Tiles_Foreground3", -32);
layer_depth("Assets_BG", 201);
layer_depth("Foreground_Ground1", -300);
layer_depth("Foreground_escape", -350);
layer_depth("Backgrounds_Ground1", 250);
parrallax_load();
