scene = 1;
cutscene_timer = 0;
obj_pl.x = 135;
obj_pl.y = 150;
obj_pl.image_alpha = 1;
obj_pl.image_angle = 0;
obj_pl.direction = 180;
robot_part[0] = 0;
robot_part[1] = 0;
robot_part[2] = 0;
robot_part[3] = 0;
instance_create(85, 150, obj_ceroba_npc);
obj_ceroba_npc.npc_direction = "right";
scr_cutscene_start();
