starting_point_x = x;
starting_point_y = y;
draw_position_x = starting_point_x;
draw_position_y = starting_point_y;
damage_disjoint_x = 0;
damage_disjoint_y = 0;
damage_disjoint_count = 0;
no_loop_damage_disjoint_count = false;
image_speed_default = 0.04;
image_speed = image_speed_default;
image_index = 0;
path_speed_default = 0.5;
path_start(pt_froggit_intro_head_yellow, 0.5, path_action_continue, 0);
