event_inherited();
message[0] = "* Dear owners of dilapidated#  cabin:";
message[1] = "* First, I am very sorry that#  your cabin is so dilapidated.";
message[2] = "* Like, I don't know what#  happened to it, but I'm sure it#  was unfortunate.";
message[3] = "* Second, I am sorry that some of#  your wood has gone missing.";
message[4] = "* According to the Royal Guard#  guide book section forty-two,#  paragraph one,";
message[5] = "* So long as notice is given to#  the original owner at least two#  business days prior,";
message[6] = "* Any and all eyesores can be#  repurposed for puzzles or other#  diversions.";
message[7] = "* Well, I didn't know how to#  contact you, but consider this#  notice!";
message[8] = "* ...Unfortunately not of the#  prior variety, but you know...#  notice.";
