conveyor_puzzle_activate = false;
conveyor_puzzle_countdown = 4;
conveyor_puzzle_active = false;
conveyor_spawn_item = false;
conveyor_item_number = 9;
conveyor_item_number_max = conveyor_item_number;
conveyor_item_number_wrong = 3;
conveyor_item_offset = 80;
conveyor_item_offset_max = conveyor_item_offset;
conveyor_item_type_last = "none";
conveyor_item_type_repeat_count = 0;
conveyor_item_type_repeat_count_max = 1;
conveyor_item_secret = 7;
hint_button_alpha = 0;
layer_set_visible("MachineFront", true);
