letter_array = -1;
letter_current = 1;
letter_waiter = 0;
line_current = 0;
letter_speed = 1;
sndfnt = snd_talk_default;
message[0] = "";
message_current = 0;
message_advance = false;
text_x[1] = 20;
text_y[1] = 100;
text_x_mod = 0;
text_y_mod = 0;
shake = false;
global.dialogue_open = true;
draw_set_font(fnt_main);
str_width = string_width("w");
