draw_set_font(fnt_main);
draw_set_alpha(draw_alpha);
draw_set_color(c_black);
draw_text(9, 219, string_hash_to_newline("File 1 Loaded"));
draw_text(10, 219, string_hash_to_newline("File 1 Loaded"));
draw_text(11, 219, string_hash_to_newline("File 1 Loaded"));
draw_text(11, 220, string_hash_to_newline("File 1 Loaded"));
draw_text(11, 221, string_hash_to_newline("File 1 Loaded"));
draw_text(10, 221, string_hash_to_newline("File 1 Loaded"));
draw_text(9, 221, string_hash_to_newline("File 1 Loaded"));
draw_text(9, 220, string_hash_to_newline("File 1 Loaded"));
draw_set_color(c_yellow);
draw_text(10, 220, string_hash_to_newline("File 1 Loaded"));
draw_set_alpha(1);
