spr_walk = spr_kibidi_walk;
spr_scared = spr_kibidi_scared;
spr_dead = spr_kibidi_dead;
spr_stun = spr_kibidi_stun;
scr_collision_init();
state = baddiestates.move;
scaredtimer = 0;
xscale = sign(image_xscale);
grav = 0.5;
movespeed = 0;
image_speed = 0.35;
stunbuffer = 15;
hitHsp = 0;
hitVsp = 0;
event_inherited();
hitX = y;
hitY = x;
hitstuntimer = 0;
hurtboxID = instance_create_depth(x, y, depth, obj_baddiehurtbox);
hurtboxID.baddieID = other;
pal = random_range(0, 3);
