ini_open("saveData.ini");
var i = 0;
var smoothcam = options[i].data.toggle;
ini_write_real("Option", "smoothcamera", smoothcam);
global.smoothcam = smoothcam;
i++;
var angle_rot = options[i].data.toggle;
ini_write_real("Option", "anglerotation", angle_rot);
global.anglerotation = angle_rot;
i++;
var danikyo = options[i].data.toggle;
ini_write_real("Option", "danikyo", danikyo);
global.danikyo = danikyo;
i++;
var unfocus = options[i].data.toggle;
ini_write_real("Option", "unfocus", unfocus);
global.unfocus = unfocus;
i++;
obj_pause.dsipalette = options[i].data.index;
trace("saved extraopts");
