image_speed = 0;
hurtpoints = 0;
timepoints = 0;
escapetimepoints = 0;
treasurepoints = 0;
lastbesttimeminutes = 99;
lastbesthurt = 99;
lastbesttimeseconds = 99;
image_index = global.levelname != "tutorial";
depth = 2;
endgate = 0;
cutscene = 0;
locked = false;
uparrowid = noone;
