event_inherited();
lookDirection = 2;
spriteDown = spr_harry_left;
spriteLeft = spr_harry_left;
spriteRight = spr_harry_right;
spriteUp = spr_harry_right;
spriteDownTalk = spr_harry_left_haha;
spriteLeftTalk = spr_harry_left_talk;
spriteRightTalk = spr_harry_right_talk;
spriteUpTalk = spr_harry_right_haha;
talkChar = "har";
fly = false;
flySpeed = 1.5;
siner = 0;
amp = 0;
