event_inherited();
spriteLeft = spr_aaxel_left;
spriteUp = spr_aaxel_up;
spriteRight = spr_aaxel_right;
spriteDown = spr_aaxel_down;
image_speed = 0;
siner = 0;
drawY = y;
jacket = true;
shadow = true;
