damage_number = scr_determine_damage_number_enemy("decibat", "void", "void");
image_alpha = 0;
image_angle = 270;
image_xscale = 1.5;
image_yscale = 1.5;
image_angle_min = 225;
image_angle_max = 315;
move_speed = 4;
can_move = false;
change_type = false;
audio_play_sound(snd_decibat3bigwaves, 20, 0);
