event_inherited();
actor_shake_init(true);
evil = evac(2) || ruth_enabled();
state = (0 << 0);
jumpSprite = spr_chara_jump;
jumpProgress = 0;
jumpStartX = 0;
jumpStartY = 0;
jumpX = 0;
jumpY = 0;
moveDirection = 0;
moveSpeed = 0;
moveSpeedAccel = 0.05;
moveSpeedMax = 2;
moveFrameIndex = 0;
peerIndex = -1;
charaShake = 0;
charaOffset = 0;
creditsTimer = 0;
collapseTimer = 0;
