scr_collision_init();
depth = 4;
image_speed = 0.35;
is_grabbed = 0;
waitTimer = 5;
old_hsp = 0;
max_vsp = 0;
hsp = 0;
vsp = 0;
grav = 0;
farBuffer = 0;
mask_index = obj_player.spr_mask;
candyindex = 0;
isReady = false;
