with (obj_dialogue_box_battle_transformation_any)
    event_user(0);

instance_destroy(obj_battle_enemy_attack_guardener_seed);
instance_destroy(obj_battle_enemy_attack_guardener_launcher);
instance_destroy(obj_battle_enemy_attack_guardener_launcher_fadein);
