with (obj_dialogue_box_battle_transformation_any)
    event_user(0);

instance_destroy(obj_battle_enemy_attack_guardener_arm);
instance_destroy(obj_battle_enemy_attack_guardener_gear_piece_big);
instance_destroy(obj_battle_enemy_attack_guardener_gear_piece_small);
instance_destroy(obj_battle_enemy_attack_guardener_launcher_explosion);
instance_destroy(obj_battle_enemy_attack_guardener_launcher_destroyable);
instance_destroy(obj_battle_enemy_attack_guardener_launcher_destroyable_fadein);
