event_inherited();
up_sprite = cdalv_up;
right_sprite = cdalv_right;
down_sprite = cdalv_down;
left_sprite = cdalv_left;
up_sprite_idle = cdalv_up;
right_sprite_idle = cdalv_rightt;
down_sprite_idle = cdalv_downt;
left_sprite_idle = cdalv_leftt;
scene = 0;
actor_speed = 2;
