image_speed = 0.35;
depth = 2;
idlespr = spr_ratblock;
bumpspr = spr_ratblock_bump;
deadspr = spr_ratblock_dead;
deadxoff = 0;
deadyoff = sprite_height / 2;
ratsniffsnd = event_instance("event:/sfx/enemy/ratsniff");
shouldsniff = true;
event_set_3d_position(ratsniffsnd, x, y, 0);
